-- =============================================================================
-- AMEXAN Medical Knowledge Compiler - R5 acute asthma pathway
-- Paediatric + adult acute asthma management grounded to Baby Nelson p183-186
-- (claims BNR-0008..BNR-0012). Upgrades PROT-ASTHMA-ACUTE to a full pathway.
-- GENERATED FILE - do not edit by hand. Regenerate with:
--   python knowledge-compiler/build_r5_asthma.py <out>
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. knowledge.source_claim - asthma claims (Baby Nelson p183-186)
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.source_claim (claim_id, claim_code, source_version_id, chapter_id, chunk_id, page_start, page_end, claim_type, claim_kind, claim_text, knowledge_type, contract, confidence, status) VALUES
   ('fe8ed9e5-5f09-552b-8cd7-6806f31ce04b', 'BNR-0008', 'NELSON_ILLUSTRATED_2017', 'BN-C01', 'eaf04089-8b6a-5d90-9569-56dc0394cb66', '183', '183', 'PAEDIATRIC_RESPIRATORY', 'threshold', 'Acute asthma severity assessment (mild / moderate / severe): consciousness (absent vs agitated-confused), cyanosis (absent vs likely), dyspnoea (walking vs talking vs at rest), speech (sentences vs phrases vs words), pulse (normal vs mild vs marked tachycardia, >180 bpm in young), pulsus paradoxus (normal vs <20 vs 20-40 mmHg), wheeze (end-expiratory vs holosystolic vs exp+insp, may be quiet), retractions (absent vs common vs usual), peak expiratory flow (>=70% vs 40-69% vs <40%), oximetry in air (>95% vs 90-95% vs <90%), PaCO2 (<42 vs >42 mmHg).', 'medicine', '{"what_is_it":"paediatric asthma severity grid","what_fact_produces":"SPEECH_PATTERN, SPO2, PEF, HEART_RATE, WHEEZE_PRESENT, CYANOSIS","source_support":"Illustrated Baby Nelson p183"}'::jsonb, 0.9, 'VERIFIED'),
   ('b8781f55-feec-5c00-9374-61248ee84c22', 'BNR-0009', 'NELSON_ILLUSTRATED_2017', 'BN-C01', 'eaf04089-8b6a-5d90-9569-56dc0394cb66', '183', '183', 'PAEDIATRIC_RESPIRATORY', 'management', 'Emergency department treatment of acute asthma exacerbation: inhaled SABA (salbutamol) 2.5-5 mg by nebulizer with saline up to 3 treatments in 1 hour OR 2-6 puffs SABA by MDI (puff=100 mcg); ipratropium bromide 125-250 mcg by nebulizer if no adequate response to the first salbutamol nebulizer (repeat every 20 minutes for the first hour only); oral corticosteroids 1-2 mg/kg in divided doses in moderate to severe exacerbations to hasten recovery and prevent recurrence; epinephrine (1:1000) 0.3-0.5 mg IM or SC may be given in severe cases.', 'guideline_activity', '{"what_is_it":"acute asthma ED treatment","what_connects_to":"protocol step (acute asthma)","source_support":"Illustrated Baby Nelson p183"}'::jsonb, 0.9, 'VERIFIED'),
   ('e1623fd6-c7b6-5bb1-bed4-525d81901bf4', 'BNR-0010', 'NELSON_ILLUSTRATED_2017', 'BN-C01', 'eaf04089-8b6a-5d90-9569-56dc0394cb66', '183', '183', 'PAEDIATRIC_RESPIRATORY', 'red_flag', 'Signs of acute severe asthma with imminent respiratory arrest: drowsy or confused, paradoxical thoracoabdominal movement, absence of wheeze, bradycardia and absent pulsus paradoxus (due to respiratory muscle fatigue).', 'medicine', '{"what_is_it":"imminent arrest asthma signs","what_fact_produces":"CONFUSION, CYANOSIS, WHEEZE_PRESENT","source_support":"Illustrated Baby Nelson p183"}'::jsonb, 0.9, 'VERIFIED'),
   ('2c3790e2-848a-55c2-b522-daaf9275bc5a', 'BNR-0011', 'NELSON_ILLUSTRATED_2017', 'BN-C01', 'd00bcd9e-a52b-5cac-adf8-0db3493f2071', '185', '185', 'PAEDIATRIC_RESPIRATORY', 'management', 'Hospital/PICU admission for asthma: PICU is indicated for severe respiratory distress or concern for potential respiratory failure and arrest. Inpatient action plan: cardio-pulmonary monitoring, oxygen, salbutamol nebulizer every 20 min as needed then every 1-4 hr, or continuous nebulization with oxygen 5-15 mg/hr; corticosteroids short course 3-7 days (oral prednisone 1-2 mg/kg, or parenteral methylprednisolone or hydrocortisone); ipratropium bromide nebulizer (poor evidence, no longer recommended).', 'guideline_activity', '{"what_is_it":"hospital/PICU asthma care","what_connects_to":"protocol step (acute asthma)","source_support":"Illustrated Baby Nelson p185"}'::jsonb, 0.9, 'VERIFIED'),
   ('228bc75c-3050-5963-aac7-e874113fa744', 'BNR-0012', 'NELSON_ILLUSTRATED_2017', 'BN-C01', '29895463-fd2b-5584-ab57-46065073a0f7', '186', '186', 'PAEDIATRIC_RESPIRATORY', 'management', 'After asthma exacerbation resolution: space SABA gradually; continue steroids for the full 3-7 days; start controller therapy; families of all children with asthma should have a written action plan to guide recognition and management of exacerbations; with a history of life-threatening episodes, especially abrupt-onset, consider providing an epinephrine autoinjector and possibly portable oxygen at home.', 'guideline_activity', '{"what_is_it":"post-exacerbation asthma action plan","what_connects_to":"education (action plan), controller therapy","source_support":"Illustrated Baby Nelson p186"}'::jsonb, 0.9, 'VERIFIED')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 1. medication concepts + knowledge.medication - asthma armamentarium
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.concept (id, concept_code, concept_type, canonical_name, display_name, status) VALUES
   ('90950505-c0c9-5cc9-beea-802eb374ed4f', 'CNS-MED-SALBUTAMOL', 'medication', 'Salbutamol', 'Salbutamol', 'active'),
   ('d2c6a90b-6371-5728-a92b-53a66011725a', 'CNS-MED-IPRATROPIUM', 'medication', 'Ipratropium bromide', 'Ipratropium bromide', 'active'),
   ('4ff8ef68-d825-5838-a22c-349852472934', 'CNS-MED-PREDNISOLONE', 'medication', 'Prednisolone', 'Prednisolone', 'active'),
   ('a6dd41a1-0981-5a7d-9840-f764857009ae', 'CNS-MED-EPINEPHRINE', 'medication', 'Epinephrine (adrenaline)', 'Epinephrine (adrenaline)', 'active'),
   ('462f5f47-8199-571c-869c-a2307d720ca6', 'CNS-MED-MAGNESIUM-SULPHATE', 'medication', 'Magnesium sulphate', 'Magnesium sulphate', 'active'),
   ('53999c46-ae05-5d91-bd3a-62fdf8b83c68', 'CNS-MED-AMINOPHYLLINE', 'medication', 'Aminophylline', 'Aminophylline', 'active'),
   ('d5adcaf4-6c1d-5abf-87b4-f89e7d993cca', 'CNS-MED-BECLOMETASONE', 'medication', 'Beclometasone dipropionate', 'Beclometasone dipropionate', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.medication (id, concept_id, medication_code, generic_name, drug_class, route_options, formulations, contraindications, evidence_source, status) VALUES
   ('a53c8d0b-29ca-534b-b019-bf7429ce3426', '90950505-c0c9-5cc9-beea-802eb374ed4f', 'MED-SALBUTAMOL', 'Salbutamol', 'Short-acting beta-2 agonist (SABA)', '["inhalation","nebuliser","intravenous"]'::jsonb, '["MDI 100 mcg/puff","nebuliser solution","IV infusion"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Illustrated Baby Nelson p183-186 (BNR-0009/0011/0012) - verify against local formulary.', 'active'),
   ('eda0975c-b0c9-5ee9-917b-48a20ebc10ff', 'd2c6a90b-6371-5728-a92b-53a66011725a', 'MED-IPRATROPIUM', 'Ipratropium bromide', 'Short-acting muscarinic antagonist (SAMA)', '["inhalation","nebuliser"]'::jsonb, '["nebuliser solution"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Illustrated Baby Nelson p183-186 (BNR-0009/0011/0012) - verify against local formulary.', 'active'),
   ('6917923a-6709-531e-9eb0-8866d3e9ed64', '4ff8ef68-d825-5838-a22c-349852472934', 'MED-PREDNISOLONE', 'Prednisolone', 'Oral corticosteroid', '["oral"]'::jsonb, '["tablet","soluble tablet"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Illustrated Baby Nelson p183-186 (BNR-0009/0011/0012) - verify against local formulary.', 'active'),
   ('5ca33ad7-9439-5cbf-83da-725c5af2bd87', 'a6dd41a1-0981-5a7d-9840-f764857009ae', 'MED-EPINEPHRINE', 'Epinephrine (adrenaline)', 'Sympathomimetic (alpha+beta)', '["intramuscular","subcutaneous"]'::jsonb, '["1:1000 ampoule"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Illustrated Baby Nelson p183-186 (BNR-0009/0011/0012) - verify against local formulary.', 'active'),
   ('ab3887f7-86f8-5f9b-abe1-31b23f0d6e0f', '462f5f47-8199-571c-869c-a2307d720ca6', 'MED-MAGNESIUM-SULPHATE', 'Magnesium sulphate', 'Electrolyte / bronchodilator adjunct', '["intravenous"]'::jsonb, '["IV infusion"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Illustrated Baby Nelson p183-186 (BNR-0009/0011/0012) - verify against local formulary.', 'active'),
   ('477f6044-0a09-5041-87b0-929d37bb749e', '53999c46-ae05-5d91-bd3a-62fdf8b83c68', 'MED-AMINOPHYLLINE', 'Aminophylline', 'Theophylline (phosphodiesterase inhibitor)', '["intravenous"]'::jsonb, '["IV infusion"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Illustrated Baby Nelson p183-186 (BNR-0009/0011/0012) - verify against local formulary.', 'active'),
   ('cc9be800-8fdd-5ac8-a33f-089e22119ec6', 'd5adcaf4-6c1d-5abf-87b4-f89e7d993cca', 'MED-BECLOMETASONE', 'Beclometasone dipropionate', 'Inhaled corticosteroid (ICS)', '["inhalation"]'::jsonb, '["MDI 100 mcg/puff"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Illustrated Baby Nelson p183-186 (BNR-0009/0011/0012) - verify against local formulary.', 'active')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 1b. knowledge.monitoring - MON-PEF (peak expiratory flow)
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.concept (id, concept_code, concept_type, canonical_name, display_name, status) VALUES
   ('09930b64-4da9-5d01-97f8-37aa779bbbdb', 'CNS-PEF', 'monitoring', 'Peak expiratory flow', 'Peak expiratory flow', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.monitoring (id, concept_id, monitoring_code, canonical_name, description, target_type, unit, body_system_code, normal_low, normal_high, status) VALUES
   ('3e8e79d7-ae3e-5011-b94a-f36ce8021865', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-PEF'), 'MON-PEF', 'Peak expiratory flow', 'Peak expiratory flow rate - grades asthma severity (>=70% mild, 40-69% moderate, <40% severe) and tracks response.', 'numeric', '% predicted', 'RESPIRATORY', NULL, NULL, 'active')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 1c. knowledge.drug_dose_reference - acute asthma doses (both populations)
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('ff0ccfd4-221c-5738-a59a-47c4b68c5c9c', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-SALBUTAMOL'), 'paediatric', 'ASTHMA', 'inhalation', '2.5-5 mg by nebulizer (or 2-6 puffs by MDI, puff=100 mcg); repeat up to 3 treatments in 1 hour', 'every 20 minutes in the first hour, then every 3-4 hours as needed', 'during exacerbation', 'Illustrated Baby Nelson p183-186 (BNR-0009)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('8262b421-0d2c-53b5-871d-995a95fd04fa', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'drug_dose_reference', 'ff0ccfd4-221c-5738-a59a-47c4b68c5c9c', 'DOSE:MED-SALBUTAMOL', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('b44ee5aa-99dc-58bb-b7ce-dc68565d596f', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-SALBUTAMOL'), 'adult', 'ASTHMA', 'inhalation', '2.5-5 mg by nebulizer (or 100-200 mcg by MDI); repeat up to 3 treatments in 1 hour', 'every 20 minutes in the first hour, then every 3-4 hours as needed', 'during exacerbation', 'Illustrated Baby Nelson p183-186 (BNR-0009)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('8262b421-0d2c-53b5-871d-995a95fd04fa', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'drug_dose_reference', 'b44ee5aa-99dc-58bb-b7ce-dc68565d596f', 'DOSE:MED-SALBUTAMOL', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('d011d902-c196-5b5c-b78a-64d5b4245504', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-IPRATROPIUM'), 'paediatric', 'ASTHMA', 'inhalation', '125-250 mcg by nebulizer if no adequate response to first salbutamol', 'repeat every 20 minutes (first hour only)', 'first hour', 'Illustrated Baby Nelson p183-186 (BNR-0009)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('3b9eb63b-7a5f-5d76-a710-ce999232e2f7', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'drug_dose_reference', 'd011d902-c196-5b5c-b78a-64d5b4245504', 'DOSE:MED-IPRATROPIUM', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('a18fe14e-daf7-50b2-85fe-67a389e9eef7', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-IPRATROPIUM'), 'adult', 'ASTHMA', 'inhalation', '250-500 mcg by nebulizer if no adequate response to first salbutamol', 'repeat every 20 minutes (first hour only)', 'first hour', 'Illustrated Baby Nelson p183-186 (BNR-0009)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('3b9eb63b-7a5f-5d76-a710-ce999232e2f7', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'drug_dose_reference', 'a18fe14e-daf7-50b2-85fe-67a389e9eef7', 'DOSE:MED-IPRATROPIUM', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('00e76472-01a4-5fb0-a88a-9aae108303cd', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-PREDNISOLONE'), 'paediatric', 'ASTHMA', 'oral', '1-2 mg/kg in divided doses (max 60 mg/day)', 'once daily (or divided doses)', '3-7 days', 'Illustrated Baby Nelson p183-186 (BNR-0009)', TRUE, 'mg_per_kg', 1, 2, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('705aa49f-f477-5d78-8f3b-7e90598a0599', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'drug_dose_reference', '00e76472-01a4-5fb0-a88a-9aae108303cd', 'DOSE:MED-PREDNISOLONE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('ff885726-9345-5a09-8899-ab4631fe979d', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-PREDNISOLONE'), 'adult', 'ASTHMA', 'oral', '1-2 mg/kg in divided doses (max 60 mg/day)', 'once daily (or divided doses)', '3-7 days', 'Illustrated Baby Nelson p183-186 (BNR-0009)', TRUE, 'mg_per_kg', 1, 2, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('705aa49f-f477-5d78-8f3b-7e90598a0599', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'drug_dose_reference', 'ff885726-9345-5a09-8899-ab4631fe979d', 'DOSE:MED-PREDNISOLONE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('9d1c5a25-1161-543c-8858-d7f99343c430', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-EPINEPHRINE'), 'paediatric', 'ASTHMA', 'intramuscular', '0.3-0.5 mg IM or SC (1:1000)', 'single dose; may repeat if needed', 'severe cases only', 'Illustrated Baby Nelson p183-186 (BNR-0009)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('9479cff6-c64d-5b76-b898-981aab93d863', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'drug_dose_reference', '9d1c5a25-1161-543c-8858-d7f99343c430', 'DOSE:MED-EPINEPHRINE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('065beebb-14e1-5b25-83f5-d5c928d6e820', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-EPINEPHRINE'), 'adult', 'ASTHMA', 'intramuscular', '0.3-0.5 mg IM or SC (1:1000)', 'single dose; may repeat if needed', 'severe cases only', 'Illustrated Baby Nelson p183-186 (BNR-0009)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('9479cff6-c64d-5b76-b898-981aab93d863', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'drug_dose_reference', '065beebb-14e1-5b25-83f5-d5c928d6e820', 'DOSE:MED-EPINEPHRINE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('25e17645-d748-55d4-8391-c5a1cd473b43', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-MAGNESIUM-SULPHATE'), 'paediatric', 'ASTHMA', 'intravenous', '25-75 mg/kg IV over 20 minutes (max 2.5 g)', 'single infusion over 20 minutes', 'critically ill only', 'Illustrated Baby Nelson p183-186 (BNR-0011)', TRUE, 'mg_per_kg', 25, 75, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('bd81b0fa-8485-56ca-b406-839d303a004d', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0011'), 'drug_dose_reference', '25e17645-d748-55d4-8391-c5a1cd473b43', 'DOSE:MED-MAGNESIUM-SULPHATE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('a72eee41-5682-5b16-9a29-3d0eca5ae0d3', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-MAGNESIUM-SULPHATE'), 'adult', 'ASTHMA', 'intravenous', '1.2-2 g IV over 20 minutes', 'single infusion over 20 minutes', 'critically ill only', 'Illustrated Baby Nelson p183-186 (BNR-0011)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('bd81b0fa-8485-56ca-b406-839d303a004d', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0011'), 'drug_dose_reference', 'a72eee41-5682-5b16-9a29-3d0eca5ae0d3', 'DOSE:MED-MAGNESIUM-SULPHATE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('460a74fb-f540-5efa-b807-a697b147815c', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-AMINOPHYLLINE'), 'paediatric', 'ASTHMA', 'intravenous', 'Loading 5-10 mg/kg over 1 hour, then maintenance 1 mg/kg/hour (0.7 mg/kg/hour if >10 years)', 'loading over 1 hour, then maintenance infusion', 'while critically ill', 'Illustrated Baby Nelson p183-186 (BNR-0011)', TRUE, 'mg_per_kg', 5, 10, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('c960bcb8-dd2d-5646-93fb-24d4cbc8aa3c', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0011'), 'drug_dose_reference', '460a74fb-f540-5efa-b807-a697b147815c', 'DOSE:MED-AMINOPHYLLINE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('af989ad1-6706-50f8-a0c1-442542ed4e7b', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-AMINOPHYLLINE'), 'adult', 'ASTHMA', 'intravenous', 'Loading 6 mg/kg over 20-30 min, then 0.5-0.9 mg/kg/hour', 'loading then maintenance infusion', 'while critically ill', 'Illustrated Baby Nelson p183-186 (BNR-0011)', TRUE, 'mg_per_kg', 5, 6, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('c960bcb8-dd2d-5646-93fb-24d4cbc8aa3c', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0011'), 'drug_dose_reference', 'af989ad1-6706-50f8-a0c1-442542ed4e7b', 'DOSE:MED-AMINOPHYLLINE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('19410c8d-8a02-50ed-aeb2-aafc1e4bf96a', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-BECLOMETASONE'), 'paediatric', 'ASTHMA', 'inhalation', 'Controller therapy after exacerbation - 100-200 mcg twice daily (MDI)', 'twice daily (continue during and after exacerbation)', 'ongoing controller', 'Illustrated Baby Nelson p183-186 (BNR-0012)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('3e6d07ee-8bc8-5c54-a3dc-e40530ea99e8', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0012'), 'drug_dose_reference', '19410c8d-8a02-50ed-aeb2-aafc1e4bf96a', 'DOSE:MED-BECLOMETASONE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('a6be0d4b-f607-5d4c-89e6-b4036691493e', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-BECLOMETASONE'), 'adult', 'ASTHMA', 'inhalation', 'Controller therapy after exacerbation - 100-200 mcg twice daily (MDI)', 'twice daily (continue during and after exacerbation)', 'ongoing controller', 'Illustrated Baby Nelson p183-186 (BNR-0012)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('3e6d07ee-8bc8-5c54-a3dc-e40530ea99e8', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0012'), 'drug_dose_reference', 'a6be0d4b-f607-5d4c-89e6-b4036691493e', 'DOSE:MED-BECLOMETASONE', 'derived_from')   ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 1d. knowledge.medication_condition - asthma treatment links
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.medication_condition (id, medication_id, condition_id, role, weight) VALUES
   ('40701cd7-dd70-59a0-9f46-75f1e98123a0', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-SALBUTAMOL'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 'treatment', '1.00'),
   ('1e00e819-b723-54a7-9798-407366993276', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-IPRATROPIUM'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 'treatment', '0.80'),
   ('ded273e3-9307-521e-9d93-0ccb787dcf4c', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-PREDNISOLONE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 'treatment', '0.90'),
   ('119d7a5a-3255-5aed-8482-739a39ecc2c6', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-EPINEPHRINE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 'treatment', '0.60'),
   ('2bf43bb6-3c1a-509d-b656-2d6de18b4a5e', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-MAGNESIUM-SULPHATE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 'treatment', '0.50'),
   ('fbf53622-2567-5e00-b33e-f1dd6c885bf0', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-AMINOPHYLLINE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 'treatment', '0.40'),
   ('f3278808-c409-584e-9575-0e226a8306e0', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-BECLOMETASONE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 'supportive', '0.70')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. PROT-ASTHMA-ACUTE - full 12-step pathway (population 'both')
-- ---------------------------------------------------------------------------
UPDATE knowledge.protocol SET canonical_name = 'Acute asthma pathway', population = 'both', status = 'active',
       description = 'Population-aware acute asthma exacerbation pathway: severity grading, emergency treatment, monitoring, escalation, disposition, written action plan, education.',
       source_reference = 'Illustrated Baby Nelson p183-186 (BNR-0008..0012)' WHERE protocol_code = 'PROT-ASTHMA-ACUTE';

INSERT INTO knowledge.protocol_condition (id, protocol_id, condition_id, is_primary) VALUES
   ('99e1550b-53fd-59c8-8a68-ae8fed6e5e5a', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), true)
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_step (id, protocol_id, step_code, step_label, step_type, sequence_no, instruction, rationale, required) VALUES
   ('65c502fa-4ead-5ddc-ad11-f37454c3b4f1', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-01', 'Confirm acute asthma presentation', 'eligibility', '10', 'Establish recurrent/presenting wheeze, cough, dyspnoea and chest tightness with variable obstruction; elicit triggers, nocturnal symptoms and atopic history.', 'Asthma is episodic and variable; triggers and atopy support the diagnosis.', TRUE),
   ('01223c58-47eb-5d7f-9a3c-c375e4127c55', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-02', 'Assess severity immediately', 'red_flag', '20', 'Grade mild/moderate/severe by consciousness, speech (sentences/phrases/words), pulse, pulsus paradoxus, wheeze, retractions, PEF, oximetry in air and cyanosis.', 'Severity grading drives treatment intensity and disposition (BNR-0008).', TRUE),
   ('c0610765-6e76-5bac-a04e-504df142f463', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-03', 'Screen for imminent respiratory arrest', 'red_flag', '30', 'Look for drowsy/confused state, paradoxical thoracoabdominal movement, absence of wheeze, bradycardia and absent pulsus paradoxus.', 'Respiratory muscle fatigue precedes arrest; these signs mandate immediate escalation (BNR-0010).', TRUE),
   ('faf8cb49-9549-566a-9209-8710bd2817a3', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-04', 'Deliver emergency treatment', 'treatment', '40', 'High-flow oxygen to keep SpO2 >92%; salbutamol 2.5-5 mg nebulizer or 2-6 puffs MDI repeated up to 3 treatments in the first hour; ipratropium 125-250 mcg nebulizer if no response to first salbutamol (first hour only); oral corticosteroids 1-2 mg/kg in moderate-severe; epinephrine 0.3-0.5 mg IM/SC in severe cases.', 'Rapid bronchodilation + corticosteroids shorten recovery and prevent recurrence (BNR-0009).', TRUE),
   ('14a0d8a0-7884-510c-b23b-07dcbf0c4349', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-05', 'Monitor response', 'monitoring', '50', 'Reassess at 1 hour: PEF >70% predicted/personal best, SpO2 >92% in room air for 4 hours, normal physical findings; trend pulse, respiratory effort and wheeze.', 'Outcome at 1 hour determines discharge, admission or escalation (BNR-0009).', TRUE),
   ('53eb4e9a-7f4c-5ac0-8c7f-8e9d4ed7c92b', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-06', 'Determine disposition', 'disposition', '60', 'Good outcome at 1 hour: discharge home with written action plan. Moderate-severe not improving after 1-2 hours of intensive treatment: admit. Severe respiratory distress or concern for respiratory failure/arrest: PICU.', 'High-risk patients (previous ICU admission, 2+ hospitalisations or 3+ ED visits in past year) warrant admission (BNR-0011).', TRUE),
   ('49ff79b5-6614-5f04-978c-81b46078ec18', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-07', 'Provide hospital care', 'treatment', '70', 'Cardio-pulmonary monitoring, oxygen, salbutamol nebulizer every 20 min then every 1-4 hours, or continuous nebulization 5-15 mg/hr; oral prednisolone 1-2 mg/kg or parenteral methylprednisolone/hydrocortisone for 3-7 days.', 'Inpatient care delivers intensive bronchodilation and corticosteroids under observation (BNR-0011).', TRUE),
   ('5ab2a39f-12af-515b-8f30-85bebcc7cf34', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-08', 'Escalate for persistent severe / critical illness', 'escalation', '80', 'If persistent severe dyspnoea with high-flow oxygen requirements: IV access, electrolytes/glucose/ABG, CXR if life-threatening or suspected pneumothorax, IV maintenance fluids at 70-80% of maintenance, IV salbutamol (watch potassium + ECG), epinephrine IM/SC, magnesium sulphate 25-75 mg/kg (max 2.5 g) IV over 20 min, aminophylline, inhaled heliox, mechanical ventilation.', 'Critically ill asthma requires intensive and multimodal therapy (BNR-0011).', TRUE),
   ('c841fd5e-ff3a-5e64-9f7d-c05147cbb5ac', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-09', 'Resolve exacerbation and step down', 'treatment', '90', 'When improved: space SABA gradually to every 3-4 hours; continue steroids for the full 3-7 days; start controller therapy.', 'Steroid taper and controller introduction prevent early relapse (BNR-0012).', TRUE),
   ('01bdf3cf-4059-5e17-a7aa-6ba78e667dec', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-10', 'Issue written action plan', 'education', '100', 'Give the family/patient a written action plan for recognition and management of future exacerbations; for life-threatening (especially abrupt-onset) episodes consider an epinephrine autoinjector and portable oxygen at home.', 'Every child/family with asthma should have a written action plan (BNR-0012).', TRUE),
   ('a64444f3-9857-59ff-8fcd-58ccafa09f84', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-11', 'Educate on inhaler technique and triggers', 'education', '110', 'Teach spacer/MDI technique, trigger avoidance, correct use of reliever vs controller, and when to seek urgent care.', 'Education improves adherence and reduces exacerbation risk.', TRUE),
   ('bc4b3a30-c4bc-5600-b1a2-7993758620a4', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), 'STEP-12', 'Close the care loop', 'follow_up', '120', 'Record severity, treatment given, response, discharge plan and follow-up; schedule controller review.', 'The episode generates continuity rather than terminating at discharge.', TRUE)
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_action (id, protocol_id, step_id, action_type, action_code, action_name, detail, urgency, sort_order) VALUES
   ('9ec2133b-61e1-5c38-a4a5-4f83319a781b', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-SPO2', 'Oxygen saturation monitoring', 'Grade severity: >95% mild, 90-95% moderate, <90% severe', 'immediate', '10'),
   ('de10e348-8d25-50cb-9e97-1343a2193022', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-PEF', 'Peak expiratory flow', 'Grade severity: >=70% mild, 40-69% moderate, <40% severe', 'immediate', '20'),
   ('3a1a1ec0-fc7d-54c8-8668-d68200c26ea3', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-HR', 'Heart rate monitoring', 'Mild tachycardia vs marked (>180 bpm in young)', 'immediate', '30'),
   ('b643be2c-700e-559a-9b04-4eba0d2fd478', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-WOB', 'Work of breathing', 'Retractions and paradoxical thoracoabdominal movement', 'immediate', '40'),
   ('d451a28a-a3b6-5e9f-ae2d-015555a9405d', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-04'), 'medicate', 'MED-SALBUTAMOL', 'Salbutamol (SABA)', '2.5-5 mg neb or 2-6 puffs MDI; repeat up to 3 treatments in 1 hr', 'immediate', '10'),
   ('4820a876-7b59-5fd4-bf1d-a6ef1b5b25b3', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-04'), 'medicate', 'MED-IPRATROPIUM', 'Ipratropium bromide (SAMA)', '125-250 mcg neb if no response to first salbutamol', 'immediate', '20'),
   ('49e233d3-1297-56b5-a338-6cbab57e56c0', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-04'), 'medicate', 'MED-PREDNISOLONE', 'Prednisolone', '1-2 mg/kg in moderate-severe exacerbations', 'urgent', '30'),
   ('e7ce9321-ac8a-5a40-8d0e-aada67ce67f8', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-04'), 'medicate', 'MED-EPINEPHRINE', 'Epinephrine', '0.3-0.5 mg IM/SC in severe cases', 'immediate', '40'),
   ('54885d81-a4fa-5898-9c92-e44530600953', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-05'), 'monitor', 'MON-PEF', 'Peak expiratory flow', 'Target PEF >70% predicted/personal best at 1 hour', 'urgent', '10'),
   ('731b2ea4-6c11-508b-990d-1eb82942dff2', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-05'), 'monitor', 'MON-SPO2', 'Oxygen saturation monitoring', 'Target SpO2 >92% in room air for 4 hours', 'urgent', '20'),
   ('fafc8df3-642f-5857-8e71-cfcb108d09b7', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-07'), 'medicate', 'MED-SALBUTAMOL', 'Salbutamol (SABA)', 'Nebulizer every 20 min then every 1-4 hr, or continuous 5-15 mg/hr', 'urgent', '10'),
   ('ba3c5211-f68c-52b2-bcdd-65463aabc4a1', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-07'), 'medicate', 'MED-PREDNISOLONE', 'Prednisolone', '1-2 mg/kg oral or parenteral methylprednisolone/hydrocortisone, 3-7 days', 'urgent', '20'),
   ('0ba993a4-dd97-5cb3-bac0-e46134bb8c5a', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-08'), 'medicate', 'MED-MAGNESIUM-SULPHATE', 'Magnesium sulphate', '25-75 mg/kg IV over 20 min (max 2.5 g)', 'urgent', '10'),
   ('d064ef57-cfc4-5d13-8a7c-1d3826968e74', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-08'), 'medicate', 'MED-AMINOPHYLLINE', 'Aminophylline', 'Loading 5-10 mg/kg over 1 hr, then 1 mg/kg/hr (0.7 if >10y)', 'urgent', '20'),
   ('65447609-1fb2-5fff-8e87-760822a4cae3', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-08'), 'medicate', 'MED-EPINEPHRINE', 'Epinephrine', '0.3-0.5 mg IM/SC for critically ill', 'urgent', '30'),
   ('08892aca-7758-52fc-8d10-a069f0838ada', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-10'), 'educate', 'EDU-ASTHMA-ACTION-PLAN', 'Asthma written action plan', 'Recognition and management of exacerbations; epinephrine autoinjector if life-threatening history', 'routine', '10'),
   ('a1ddf558-3bba-5561-97f6-71cad285456b', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-ASTHMA-INHALER-TECHNIQUE', 'Inhaler technique', 'Spacer/MDI technique and reliever vs controller use', 'routine', '10'),
   ('766b936f-936d-5721-bf6a-61716b32dd11', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-ASTHMA-TRIGGERS', 'Asthma triggers', 'Identify and avoid individual triggers', 'routine', '20'),
   ('7a5439f9-7d86-5727-8fe9-3f01cfd7c4ce', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-ASTHMA-TEACHBACK', 'Asthma teach-back', 'Confirm the family/patient can demonstrate use and recognition', 'routine', '30'),
   ('7c2429f9-466a-5011-963e-7128c7810a07', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-ASTHMA-ACUTE' AND ps.step_code = 'STEP-12'), 'educate', 'EDU-ASTHMA-CLINICIAN', 'Asthma reasoning summary', 'Render severity, evidence, phenotype comparison and rationale', 'routine', '10')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_monitoring (id, protocol_id, monitoring_id, frequency, deterioration_rule, escalation_instruction) VALUES
   ('956a458f-6bbe-56ba-a391-3f25ecfbbf14', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-SPO2'), 'Continuous during exacerbation; target >92% in air for 4 hr before discharge', 'SpO2 <92% or falling despite oxygen', 'Escalate oxygen; reassess severity; consider PICU'),
   ('739873a9-3331-5b02-98b4-0325d0e3ca83', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-PEF'), 'At baseline and at 1 hour after treatment', 'PEF <40% or failing to rise to >70% by 1 hour', 'Admit / escalate intensive treatment'),
   ('ad75f083-c360-516d-85c1-68f5615fe0f8', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-HR'), 'Continuous during exacerbation', 'Marked tachycardia (>180 bpm in young) or bradycardia', 'Bradycardia in asthma signals imminent arrest - escalate immediately'),
   ('cca5fdb1-b18a-58a3-8a69-3c9bf6d6688d', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-ASTHMA-ACUTE'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-WOB'), 'With every clinical assessment', 'New paradoxical thoracoabdominal movement or fatigue', 'Imminent respiratory failure - urgent escalation')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. knowledge.education - asthma education objects
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.concept (id, concept_code, concept_type, canonical_name, display_name, status) VALUES
   ('fb98691a-415c-5fef-b238-ca6fa624507d', 'CNS-EDU-ASTHMA-ACTION-PLAN', 'education', 'Written asthma action plan', 'Written asthma action plan', 'active'),
   ('44df82d4-b5ed-5b74-8eeb-4ff23681852a', 'CNS-EDU-ASTHMA-INHALER-TECHNIQUE', 'education', 'Correct inhaler technique', 'Correct inhaler technique', 'active'),
   ('7d4e5753-1a44-593d-93f3-c0728ad383a9', 'CNS-EDU-ASTHMA-TRIGGERS', 'education', 'Asthma trigger avoidance', 'Asthma trigger avoidance', 'active'),
   ('04da0ccf-cc7f-5f7d-aaf0-54d72b97c8de', 'CNS-EDU-ASTHMA-TEACHBACK', 'education', 'Asthma teach-back', 'Asthma teach-back', 'active'),
   ('29c7b5e9-94b1-58eb-9740-5081d3d68707', 'CNS-EDU-ASTHMA-CLINICIAN', 'education', 'Asthma reasoning summary', 'Asthma reasoning summary', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.education (id, concept_id, education_code, title, audience, content_type, language_code, literacy_level, body, status) VALUES
   ('014e2936-cd71-5c3c-aaf0-23f550b26aa8', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-ASTHMA-ACTION-PLAN'), 'EDU-ASTHMA-ACTION-PLAN', 'Written asthma action plan', 'caregiver', 'discharge', 'en', 'plain', 'A written plan for recognizing and managing asthma exacerbations: which medicines to take when symptoms worsen, when to seek urgent care, and home epinephrine/oxygen for life-threatening history (BNR-0012).', 'active'),
   ('894d1b9f-30bc-5ef1-a4c1-59933f9dd8a1', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-ASTHMA-INHALER-TECHNIQUE'), 'EDU-ASTHMA-INHALER-TECHNIQUE', 'Correct inhaler technique', 'patient', 'instruction', 'en', 'plain', 'Use a spacer with MDI: shake, insert, one puff, breathe in slowly and hold; reliever (salbutamol) for acute symptoms, controller (ICS) daily regardless of symptoms.', 'active'),
   ('354e32bc-7fef-5e85-94ba-e4de0a893c24', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-ASTHMA-TRIGGERS'), 'EDU-ASTHMA-TRIGGERS', 'Asthma trigger avoidance', 'patient', 'explanation', 'en', 'plain', 'Identify and avoid triggers such as viral infections, allergens, exercise, cold air and smoke; keep reliever available.', 'active'),
   ('73df41e7-f3fb-54b8-8697-84108e1c5855', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-ASTHMA-TEACHBACK'), 'EDU-ASTHMA-TEACHBACK', 'Asthma teach-back', 'caregiver', 'teach_back', 'en', 'plain', 'Confirm the patient/family can demonstrate inhaler use and describe when to seek urgent care before discharge.', 'active'),
   ('8e090d0d-860f-5aa6-920b-af4227ebabb7', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-ASTHMA-CLINICIAN'), 'EDU-ASTHMA-CLINICIAN', 'Asthma reasoning summary', 'clinician', 'explanation', 'en', 'plain', 'Render the acute asthma severity grade, evidence, phenotype comparison and the treatment/escalation rationale.', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.education_condition (id, education_id, condition_id, weight) VALUES
   ('b9869d6e-b22a-5eb5-83c5-926de5531234', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-ASTHMA-ACTION-PLAN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 1.0),
   ('d4cac07e-bd0f-53a2-afbe-2328c9abf445', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-ASTHMA-INHALER-TECHNIQUE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 1.0),
   ('e129031c-e4d6-58a9-a6b9-89df3caf437e', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-ASTHMA-TRIGGERS'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 1.0),
   ('14faaa4b-066a-5e81-a414-75a6e99108be', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-ASTHMA-TEACHBACK'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 1.0),
   ('f1a37846-a550-51e7-8383-370cf20e1a4b', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-ASTHMA-CLINICIAN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'ASTHMA'), 1.0)
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. governance.knowledge_object - asthma pathway objects
-- ---------------------------------------------------------------------------
INSERT INTO governance.population_context (id, population_code, name, description, applies_to_context_codes, is_active) VALUES
   ('3ff4e403-264d-5c01-98fd-07f41726886a', 'POP-BOTH', 'Both paediatric and adult', 'Protocols and knowledge objects that apply to paediatric and adult populations alike (e.g. acute asthma pathway).', ARRAY['inpatient','outpatient','emergency'], true)
  ON CONFLICT DO NOTHING;

INSERT INTO governance.knowledge_object (id, object_code, knowledge_type, canonical_name, description, source_claim_code, jurisdiction_code, population_code, evidence_level_code, lifecycle_status, confidence, is_active, status) VALUES
   ('ba89ec98-0e7c-52bb-82e4-c828aec35369', 'PROT-ASTHMA-ACUTE', 'PROTOCOL', 'Acute asthma pathway', 'Population-aware (paediatric + adult) acute asthma exacerbation pathway: severity grading, emergency treatment, monitoring, escalation, disposition, written action plan, education.', 'BNR-0009', 'JUR-GLOBAL', 'POP-BOTH', 'EV-C', 'ACTIVE', 0.95, true, 'active'),
   ('781b6303-a84b-5cc6-80f1-0299365d6f87', 'MED-SALBUTAMOL', 'DRUG', 'Salbutamol (acute asthma)', 'SABA bronchodilator for acute asthma exacerbation (BNR-0009).', 'BNR-0009', 'JUR-GLOBAL', 'POP-BOTH', 'EV-C', 'ACTIVE', 0.95, true, 'active'),
   ('2fea8a2e-a7b5-522b-84a9-ba8b156942fd', 'MED-PREDNISOLONE', 'DRUG', 'Prednisolone (acute asthma)', 'Oral corticosteroid 1-2 mg/kg for moderate-severe asthma exacerbations (BNR-0009).', 'BNR-0009', 'JUR-GLOBAL', 'POP-BOTH', 'EV-C', 'ACTIVE', 0.95, true, 'active'),
   ('72e5dfc9-3d5d-5351-a266-257b63af84e8', 'MON-PEF', 'MONITORING_RULE', 'Peak expiratory flow monitoring', 'Peak flow monitoring to grade and track asthma severity (BNR-0008).', 'BNR-0008', 'JUR-GLOBAL', 'POP-BOTH', 'EV-C', 'ACTIVE', 0.95, true, 'active'),
   ('04c16b03-dd44-5ee0-87e5-067fc6cfeffb', 'DOSE-ASTHMA', 'DOSING_RULE', 'Acute asthma dose rules', 'Population-aware dose rules for acute asthma bronchodilators and corticosteroids grounded to BNR-0009/0011/0012.', 'BNR-0009', 'JUR-GLOBAL', 'POP-BOTH', 'EV-C', 'ACTIVE', 0.95, true, 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO governance.knowledge_object_version (object_id, version_no, version_code, change_note, lifecycle_status, source_claim_code, created_by)
SELECT ko.id, 1, 'GO-V-R5-' || ko.object_code, 'R5 acute asthma pathway release (BNR-0008..0012).', 'ACTIVE', ko.source_claim_code, 'Dr A Otieno'
FROM governance.knowledge_object ko WHERE ko.object_code IN ('PROT-ASTHMA-ACUTE', 'MED-SALBUTAMOL', 'MED-PREDNISOLONE', 'MON-PEF', 'DOSE-ASTHMA')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('40cd0b91-8a27-5e24-addf-c0707a009309', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'governance.knowledge_object', 'ba89ec98-0e7c-52bb-82e4-c828aec35369', 'PROT-ASTHMA-ACUTE', 'derived_from')   ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('2443f06e-14df-587d-8db7-1c83b0e5152a', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'governance.knowledge_object', '781b6303-a84b-5cc6-80f1-0299365d6f87', 'MED-SALBUTAMOL', 'derived_from')   ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('84d7015e-3113-53b8-8c0e-46701e167666', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'governance.knowledge_object', '2fea8a2e-a7b5-522b-84a9-ba8b156942fd', 'MED-PREDNISOLONE', 'derived_from')   ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('fe378c7c-4cd9-5c61-b583-b0dfebfd3d71', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0008'), 'governance.knowledge_object', '72e5dfc9-3d5d-5351-a266-257b63af84e8', 'MON-PEF', 'derived_from')   ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('23fe55f1-b8cd-5906-a504-ab7a1eda1d7d', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BNR-0009'), 'governance.knowledge_object', '04c16b03-dd44-5ee0-87e5-067fc6cfeffb', 'DOSE-ASTHMA', 'derived_from')   ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 5. tracking.respiratory_master_matrix - asthma status
-- ---------------------------------------------------------------------------
UPDATE tracking.respiratory_master_matrix SET status='VERIFIED', source_ground='Baby Nelson p183-186 (BNR-0008..0012)',
       notes='Acute asthma pathway (both populations): severity grid, emergency treatment, monitoring, escalation, disposition, written action plan, education.',
       updated_at=now() WHERE item_code='COND-ASTHMA';
UPDATE tracking.respiratory_master_matrix SET status='VERIFIED', source_ground='Baby Nelson p183-186 (BNR-0008..0012)',
       notes='Paediatric acute asthma: severity grading, SABA/ipratropium/corticosteroids, PICU escalation, written action plan.',
       updated_at=now() WHERE item_code='COND-ASTHMA-PAED';
UPDATE tracking.respiratory_master_matrix SET status='GROUNDED', source_ground='Baby Nelson p183 (BNR-0008/0010)',
       notes='Severity grid + imminent-arrest signs + critical-care escalation covered by the asthma pathway.',
       updated_at=now() WHERE item_code='COND-ACUTE-SEVERE-ASTHMA';
UPDATE tracking.respiratory_master_matrix SET status='GROUNDED', source_ground='Baby Nelson p183-186 (BNR-0009/0012)',
       notes='SABA (salbutamol), SAMA (ipratropium), oral corticosteroids, epinephrine, magnesium, aminophylline, ICS controller dose rules.',
       updated_at=now() WHERE item_code='DRUG-BRONCHODILATOR';
UPDATE tracking.respiratory_master_matrix SET status='SEEDED', source_ground='Baby Nelson p174 (asthma vs bronchiolitis differential)',
       notes='Wheeze recognized (WHEEZE_PRESENT, COUGH_TRIGGERS); episodic/trigger/nocturnal graph not yet structured.',
       updated_at=now() WHERE item_code='SYM-WHEEZE';
