-- ============================================================================
-- R8: Kenya Paediatric Pneumonia Overlay Seed
-- Grounded to Kenya BPP 5th ed (pages 46-47, 57-58)
-- ============================================================================


-- Source
INSERT INTO knowledge.source (source_id, source_name, edition, year, source_type, authority_scope, amexan_role, description, language_code, status) VALUES
   ('SRC-KENYA-BPP', 'Kenya Ministry of Health Paediatric Pneumonia Guidelines (5th ed)', 5, '2022', 'guideline', 'JUR-KENYA', 'paediatric_management_guided', 'Clinical guidelines for under-5 illness/PCP; 5th edition.', 'en', 'ACTIVE_FOUNDATION')  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.source_version (version_id, source_id, edition, publication_year, language, status, pdf_page_offset) VALUES
   ('VV-KENYA-BPP-5', 'SRC-KENYA-BPP', 5, 2022, 'en', 'ACTIVE_FOUNDATION', 0)  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.source_section (section_id, source_version_id, section_no, section_name, amexan_layer, sort_order) VALUES
   ('KENYA-BPP-SECTION-CLINICAL', 'VV-KENYA-BPP-5', 1, 'Clinical management', 'SYSTEM', 10)  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.source_chapter (chapter_id, source_version_id, section_id, chapter_no, chapter_name, start_page, end_page, amexan_role, amexan_context, amexan_system, sort_order) VALUES
   ('KENYA-BPP-CH-PNEUMONIA', 'VV-KENYA-BPP-5', 'KENYA-BPP-SECTION-CLINICAL', 9, 'Childhood pneumonia and other severe infections (5-59 months)', 46, 50, NULL, 'paediatrics', 'paediatric_respiratory', 10)  ON CONFLICT DO NOTHING;

-- Claims (Kenya BPP 5th ed)
INSERT INTO knowledge.source_claim (claim_id, claim_code, source_version_id, chapter_id, chunk_id, page_start, page_end, claim_type, claim_kind, claim_text, knowledge_type, contract, is_compiled, confidence, status) VALUES
   ('RC:BPP-0001', 'BPP-0001', 'VV-KENYA-BPP-5', 'KENYA-BPP-CH-PNEUMONIA', NULL, '46', '46', 'definition', 'definition', 'Childhood pneumonia (Kenya BPP 5th ed, p46): any child aged 2-59 months presenting with cough and/or difficulty breathing is assessed for pneumonia. Look for general danger signs and chest indrawing.', 'guideline_activity', '{"what_is_it":"Kenya BPP childhood pneumonia assessment trigger","what_connects_to":"COUGH_PRESENT,FAST_BREATHING,DYSPNOEA","source_support":"Kenya BPP 5th ed p46"}', true, 0.9, 'VERIFIED')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.source_claim (claim_id, claim_code, source_version_id, chapter_id, chunk_id, page_start, page_end, claim_type, claim_kind, claim_text, knowledge_type, contract, is_compiled, confidence, status) VALUES
   ('RC:BPP-0002', 'BPP-0002', 'VV-KENYA-BPP-5', 'KENYA-BPP-CH-PNEUMONIA', NULL, '46', '46', 'management', 'management', 'Classification and first-line treatment (Kenya BPP 5th ed, p46): Severe pneumonia or very severe disease = any general danger sign OR chest indrawing OR stridor in a cold OR central cyanosis/SpO2<90%. Manage severe: parenteral antibiotics (IV benzylpenicillin + gentamicin, or ceftriaxone) + oxygen + refer/admit. Non-severe (no severe signs): high-dose amoxicillin 40-45 mg/kg/day divided twice daily (40-45 mg/kg PER DOSE) for 5 days.', 'guideline_activity', '{"what_is_it":"Kenya BPP severe vs non-severe pneumonia classification + treatment","what_connects_to":"MED-AMOXICILLIN,MED-GENTAMICIN,MED-CEFTRIAXONE,REF-KENYA-REFERRAL","source_support":"Kenya BPP 5th ed p46"}', true, 0.9, 'VERIFIED')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.source_claim (claim_id, claim_code, source_version_id, chapter_id, chunk_id, page_start, page_end, claim_type, claim_kind, claim_text, knowledge_type, contract, is_compiled, confidence, status) VALUES
   ('RC:BPP-0003', 'BPP-0003', 'VV-KENYA-BPP-5', 'KENYA-BPP-CH-PNEUMONIA', NULL, '46', '47', 'investigation', 'investigation', 'Assess respiratory rate, chest indrawing, stridor, central cyanosis; give pulse oximetry. Severe hypoxaemia (SpO2<90% or <60 mmHg RaO2) needs high-flow oxygen to a target of at least 90% saturation (Kenya BPP 5th ed, p46-47).', 'guideline_activity', '{"what_is_it":"Kenya BPP investigations and hypoxaemia thresholds","what_connects_to":"INV-CXR,MON-SPO2,MON-RR","source_support":"Kenya BPP 5th ed p46-47"}', true, 0.9, 'VERIFIED')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.source_claim (claim_id, claim_code, source_version_id, chapter_id, chunk_id, page_start, page_end, claim_type, claim_kind, claim_text, knowledge_type, contract, is_compiled, confidence, status) VALUES
   ('RC:BPP-0004', 'BPP-0004', 'VV-KENYA-BPP-5', 'KENYA-BPP-CH-PNEUMONIA', NULL, '47', '47', 'principle', 'principle', 'Review the child within 24-48 hours. If no improvement or worsening: treat as severe - give IV benzylpenicillin + gentamicin (or ceftriaxone), refer urgently, test for HIV and consider TB (Kenya BPP 5th ed, p47).', 'guideline_activity', '{"what_is_it":"Kenya BPP treatment-failure escalation","what_connects_to":"MED-CEFTRIAXONE,REF-KENYA-ESCALATION","source_support":"Kenya BPP 5th ed p47"}', true, 0.9, 'VERIFIED')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.source_claim (claim_id, claim_code, source_version_id, chapter_id, chunk_id, page_start, page_end, claim_type, claim_kind, claim_text, knowledge_type, contract, is_compiled, confidence, status) VALUES
   ('RC:BPP-0005', 'BPP-0005', 'VV-KENYA-BPP-5', 'KENYA-BPP-CH-PNEUMONIA', NULL, '47', '47', 'management', 'management', 'Discharge only once the child is feeding normally and has no severe signs. Teach caregivers to complete the full antibiotic course and to return immediately for return of danger signs (grunting, nasal flaring, poor feeding, chest indrawing, cyanosis). (Kenya BPP 5th ed, p47).', 'guideline_activity', '{"what_is_it":"Kenya BPP discharge teaching + danger-sign return instructions","what_connects_to":"EDU-KENYA-DANGER-SIGNS,EDU-KENYA-RETURN-CARE","source_support":"Kenya BPP 5th ed p47"}', true, 0.9, 'VERIFIED')
  ON CONFLICT DO NOTHING;
-- Protocol PROT-PNEUMONIA-KENYA-PAED
INSERT INTO knowledge.protocol (id, protocol_code, canonical_name, description, population, purpose, status, is_guideline, source_reference, configurable) VALUES
   ('d6a3df9b-bd20-5594-b96c-03743413ee49', 'PROT-PNEUMONIA-KENYA-PAED', 'Kenya paediatric pneumonia management pathway', 'Jurisdictional overlay for JUR-KENYA of the paediatric pneumonia management pathway: eligibility (2-59mo), danger-sign assessment, severe vs non-severe classification, investigation, severe (parenteral + refer) vs non-severe (high-dose amoxicillin 40-45 mg/kg/dose) treatment, 48h review and escalation, monitoring and caregiver education, follow-up. Replaces the generic protocol for Kenyan children.', 'paediatric', 'management', 'active', true, 'Kenya BPP 5th ed p46-47', false)
  ON CONFLICT DO NOTHING;

-- protocol_condition
INSERT INTO knowledge.protocol_condition (id, protocol_id, condition_id, is_primary) VALUES
   ('a3f4ec20-0076-5dcb-a101-fbdf04efe5f1', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT id FROM knowledge.condition WHERE condition_code = 'PNEUMONIA'), true)
  ON CONFLICT DO NOTHING;

-- protocol_step
INSERT INTO knowledge.protocol_step (id, protocol_id, step_code, step_label, step_type, sequence_no, instruction, rationale, required) VALUES
   ('89fc96af-1b68-5e99-9069-f176c5dfc9ce', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-01', 'Confirm childhood pneumonia', 'eligibility', 10, 'Confirm: child aged 2-59 months with cough and/or difficulty breathing.', 'Any child 2-59 months with cough and/or difficulty breathing is assessed for pneumonia; the paediatric overlay only applies within this age band (BPP-0001).', true),
   ('691a34cd-7dae-56a9-ac35-512c55cc82df', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-02', 'Assess general danger signs', 'red_flag', 20, 'Ask about and look for: inability to drink / poor feeding, persistent grunting, nasal flaring, chest indrawing, stridor in a cold, central cyanosis or SpO2<90%.', 'General danger signs and chest indrawing identify severe disease requiring urgent action (BPP-0001/BPP-0002).', true),
   ('86e79e3a-1a04-5f62-905d-1f369bbc6d59', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-03', 'Examine and stage severity', 'investigation', 30, 'Measure respiratory rate, look for chest indrawing/stridor, assess conscious state, and give pulse oximetry (SpO2).', 'RR, chest indrawing and SpO2 are the staging variables used to separate severe from non-severe disease (BPP-0003).', true),
   ('d0033c07-8667-512e-8a57-72873892b4ae', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-04', 'Classify', 'score', 40, 'Classify: Severe/non-severe. Severe if ANY general danger sign OR chest indrawing OR stridor in a cold OR SpO2<90%; otherwise non-severe.', 'Classification drives the treatment intensity: severe -> parenteral antibiotics + refer; non-severe -> high-dose oral amoxicillin (BPP-0002).', true),
   ('c45863a9-5800-5109-82e4-4926e0ded914', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-05', 'Give parenteral treatment for severe', 'treatment', 50, 'Severe: refer/admit urgently; give IV benzylpenicillin + gentamicin (or ceftriaxone); high-flow oxygen to SpO2>=90% unless COPD.', 'Severe pneumonia / very severe disease needs parenteral antibiotics and hospital-level care (BPP-0002).', true),
   ('2c3bf116-e4fb-56c9-b228-3a1cbac128e5', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-06', 'Give high-dose amoxicillin for non-severe', 'treatment', 60, 'Non-severe: high-dose amoxicillin 40-45 mg/kg per dose orally every 12 hours for 5 days (dose served from the JUR-KENYA drug_dose_reference row).', 'Non-severe pneumonia is treated with high-dose oral amoxicillin 40-45 mg/kg/dose (BPP-0002) - NOT the universal 50-90 row.', true),
   ('81c1b445-f8e0-5cbe-8d1d-3df9a5e7a2e1', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-07', 'Monitor response', 'monitoring', 70, 'Monitor SpO2 (target >=95% non-severe / >=90% severe), RR, work of breathing, feeding and temperature.', 'Close monitoring of oxygenation, effort and intake/output detects deterioration early (BPP-0003).', true),
   ('5429d66a-13ef-560f-ba4d-11b5e58a2f9c', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-08', 'Supportive care and hydration', 'treatment', 80, 'Reassess hydration; give maintenance fluids if unable to drink; treat fever with paracetamol (verify dose against formulary).', 'Dehydration and fever are managed alongside antibiotics (BPP-0002).', true),
   ('e8037896-be01-567d-bb28-660bc6fc0472', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-09', 'Give oxygen for hypoxaemia', 'treatment', 90, 'If SpO2<90%: give high-flow oxygen to a target SpO2>=90% (adults/older children >=92%); wean as the child improves.', 'Hypoxaemia is the principal cause of death in severe pneumonia and is reversible with oxygen (BPP-0003).', true),
   ('864c3c7d-4b88-522c-86ea-dafafebdf488', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-10', 'Escalate on treatment failure', 'escalation', 100, 'If no improvement or worsening within 24-48h: switch to parenteral therapy (IV benzylpenicillin + gentamicin or ceftriaxone), escalate oxygen, refer; test for HIV and consider TB.', 'Treatment failure in 1-2% of cases signals severity/misclassification and requires urgent escalation (BPP-0004).', true),
   ('e605d51e-2af2-57fa-b7d3-2fdda8a27913', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-11', 'Educate the caregiver', 'education', 110, 'Teach: complete the full antibiotic course; recognise and act on danger signs (grunting, nasal flaring, poor feeding, chest indrawing, cyanosis); return immediately if no improvement.', 'Discharge teaching reduces readmission; danger signs are the key messages (BPP-0005).', true),
   ('598c5adf-0d57-5940-a08f-b87fdd156e14', 'd6a3df9b-bd20-5594-b96c-03743413ee49', 'STEP-12', 'Close the care loop', 'follow_up', 120, 'Document the severity classification and response to treatment; arrange follow-up and link to community outreach for the 48h review.', 'A pneumonia episode feeds ongoing care and surveillance; the 48h review is a hard stop (BPP-0004).', true)  ON CONFLICT DO NOTHING;

-- protocol_action
INSERT INTO knowledge.protocol_action (id, protocol_id, step_id, action_type, action_code, action_name, detail, urgency, sort_order) VALUES
   ('1a67d85e-d8fe-56c3-ae27-126a25d98d6c', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-RR', 'Respiratory rate', 'Count respirations while appropriately settled; tachypnoea is an early severity marker (BPP-0003).', 'immediate', 10),
   ('ff051ca0-dcf4-5382-a375-fda3ca69dd22', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-SPO2', 'Oxygen saturation monitoring', 'Pulse oximetry; severe hypoxaemia defined as SpO2<90% (BPP-0003).', 'immediate', 20),
   ('fba7423e-9a85-54b3-9e1f-878a9d5e61fe', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-WOB', 'Work of breathing', 'Chest indrawing, nasal flaring, grunt - watch for progression.', 'immediate', 30),
   ('846b65d9-0194-5a83-8d31-38a99dfb61c5', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-04'), 'score', 'SCORE-KENYA-PNEUMONIA', 'Pneumonia classification score', 'Severe / non-severe / no pneumonia by Kenya BPP criteria (danger signs + chest indrawing + SpO2).', 'routine', 10),
   ('5ec1136b-b57c-5a71-b0d7-98f01480cf49', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-05'), 'refer', 'REF-KENYA-REFERRAL', 'Refer / admit for severe pneumonia', 'Parenteral antibiotics + oxygen in a facility that can provide higher-level care.', 'immediate', 10),
   ('bf7bfb10-b586-50ff-a11a-a1c90ab6d50e', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-05'), 'advice', 'ADV-KENYA-IV-AB', 'IV benzylpenicillin + gentamicin (or ceftriaxone)', 'Standard doses: benzylpenicillin 25 mg/kg IV q6h + gentamicin 7.5 mg/kg/day IM once (or ceftriaxone). Verify against formulary.', 'immediate', 20),
   ('a57fc1c8-a03e-5313-8188-e253cc34fb22', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-06'), 'advice', 'ADV-KENYA-AMOX', 'High-dose oral amoxicillin', '40-45 mg/kg per dose every 12h for 5 days; dose row served from knowledge.drug_dose_reference jurisdiction_code=JUR-KENYA. Verify against formulary.', 'immediate', 10),
   ('bd1ccebf-e2d2-5dfc-9527-ab82012191d1', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-06'), 'advice', 'ADV-KENYA-ZINC', 'Zinc supplementation', '20 mg elemental zinc daily for children 2-11 months, 10 mg for 12-59 months, for 10-14 days (WHO/Kenya integrated mg).', 'routine', 20),
   ('3e59aeed-2c2e-56cf-ab70-230ed7096f5f', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-07'), 'monitor', 'MON-SPO2', 'Oxygen saturation monitoring', 'Target >=95% (non-severe) or >=90% (severe); reassess with every clinical review.', 'routine', 10),
   ('c4d466e0-af23-58bf-80c6-3c9024501c04', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-07'), 'monitor', 'MON-RR', 'Respiratory rate monitoring', 'Tachypnoea and work of breathing tracked serially.', 'routine', 20),
   ('414b9112-e6cf-5f48-a7bb-369f6c1be671', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-07'), 'monitor', 'MON-WOB', 'Work of breathing', 'Chest indrawing, grunting, nasal flaring - watch for progression.', 'routine', 30),
   ('a3344f7e-91d5-5651-b021-94cf574d5067', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-10'), 'refer', 'REF-KENYA-ESCALATION', 'Escalate on treatment failure', 'Switch to parenteral therapy; urgent referral with oxygen support; HIV test + TB screen.', 'immediate', 10),
   ('620a1a21-7e85-5dd0-a577-4e590a84e969', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-10'), 'investigate', 'INV-CXR', 'Chest X-ray', 'If severe or no improvement: CXR to exclude concurrent/severe pathology.', 'urgent', 20),
   ('b4f0bdd9-c1a7-58ae-b387-1aa50fdccc2c', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-10'), 'investigate', 'INV-HIV', 'HIV test', 'HIV testing in severe/refractory childhood pneumonia (Kenya BPP).', 'urgent', 30),
   ('b564369e-31c3-5614-8f1f-bf21ac8eb31e', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-KENYA-DANGER-SIGNS', 'Recognise danger signs (caregiver)', 'Seek care immediately for: grunting, nasal flaring, poor feeding, chest indrawing, central cyanosis.', 'routine', 10),
   ('50c79a57-6370-5d24-bc0a-dd19c0cbd7fe', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-KENYA-TREATMENT-COMPLIANCE', 'Complete the antibiotic course', 'Give every dose of the amoxicillin exactly as prescribed for the full 5 days. Even if your child looks better, finish the antibiotics so the infection is fully cleared (Kenya BPP 5th ed, p47).', 'routine', 20),
   ('a2203c1c-483b-596f-8f8f-ff936cfb1d26', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-KENYA-RETURN-CARE', 'When to return and the 48-hour review', 'Return immediately if condition worsens or no improvement within 48 hours; attend the scheduled review. Early return saves lives (Kenya BPP 5th ed, p47).', 'routine', 30),
   ('416d5312-edda-57ea-a8cd-bca0a4558991', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-PNEUMONIA-KENYA-PAED' AND ps.step_code = 'STEP-12'), 'follow_up', 'REF-KENYA-48H-REVIEW', '48-hour review / outreach', 'Hard-stop review within 48h; link to community health outreach for follow-up.', 'routine', 10)  ON CONFLICT DO NOTHING;

-- protocol_monitoring
INSERT INTO knowledge.protocol_monitoring (id, protocol_id, monitoring_id, frequency, deterioration_rule, escalation_instruction) VALUES
   ('a4b53109-d3a1-591e-8002-7250fc0c59c9', 'd6a3df9b-bd20-5594-b96c-03743413ee49', (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-SPO2'), 'Every clinical review; target >=95% (non-severe) / >=90% (severe)', 'SpO2 <90% or falling despite oxygen, or rising work of breathing', 'Reassess severity; escalate oxygen; consider referral if severe'),
   ('f6db3b00-7f78-58fb-9755-4bf5dc4dbe5c', 'd6a3df9b-bd20-5594-b96c-03743413ee49', (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-RR'), 'Serial count at every review; age-appropriate tachypnoea thresholds', 'Persistent tachypnoea or rising work of breathing', 'Reassess severity; consider CXR/ABG; escalate'),
   ('8b424350-80ca-521b-b76f-b9b2d960c610', 'd6a3df9b-bd20-5594-b96c-03743413ee49', (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-WOB'), 'With every clinical assessment', 'New or worsening chest indrawing, grunting, nasal flaring, or cyanosis', 'Rise to severe pathway; admit; give oxygen and parenteral antibiotics')  ON CONFLICT DO NOTHING;

-- Education concepts
INSERT INTO knowledge.concept (id, concept_code, concept_type, canonical_name, display_name, status) VALUES
   ('323b5ddc-34cd-578e-9714-42b129163b60', 'CNS-EDU-KENYA-DANGER-SIGNS', 'education', 'Recognise danger signs in childhood pneumonia', 'Recognise danger signs in childhood pneumonia', 'active'),
   ('7e8d281c-6699-5f64-a2ea-990609bd38c1', 'CNS-EDU-KENYA-TREATMENT-COMPLIANCE', 'education', 'Complete the antibiotic course', 'Complete the antibiotic course', 'active'),
   ('49fb7c4e-a2db-52ee-b3cf-ff9a9b0a2bf6', 'CNS-EDU-KENYA-RETURN-CARE', 'education', 'When to return and the 48-hour review', 'When to return and the 48-hour review', 'active')  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.education (id, concept_id, education_code, title, audience, content_type, language_code, literacy_level, body, status) VALUES
   ('0425789d-94ae-5906-afe9-b45c5728060d', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-KENYA-DANGER-SIGNS'), 'EDU-KENYA-DANGER-SIGNS', 'Recognise danger signs in childhood pneumonia', 'caregiver', 'explanation', 'en', 'plain', 'Seek care immediately if your child develops: grunting, nasal flaring, poor feeding, chest indrawing, central cyanosis. These can mean severe pneumonia (Kenya BPP 5th ed, p47).', 'active'),
   ('c329b231-4f17-5a22-bbc1-b705afe130f8', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-KENYA-TREATMENT-COMPLIANCE'), 'EDU-KENYA-TREATMENT-COMPLIANCE', 'Complete the antibiotic course', 'caregiver', 'explanation', 'en', 'plain', 'Give every dose of the amoxicillin exactly as prescribed for the full 5 days. Even if your child looks better, finish the antibiotics so the infection is fully cleared (Kenya BPP 5th ed, p47).', 'active'),
   ('b224580a-972e-5f25-a1bd-6d2afbfd2a31', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-KENYA-RETURN-CARE'), 'EDU-KENYA-RETURN-CARE', 'When to return and the 48-hour review', 'caregiver', 'discharge', 'en', 'plain', 'Return immediately if condition worsens or no improvement within 48 hours; attend the scheduled review. Early return saves lives (Kenya BPP 5th ed, p47).', 'active')  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.education_condition (id, education_id, condition_id, weight) VALUES
   ('69eda27d-9e39-5c57-b2ff-678776c41f46', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-KENYA-DANGER-SIGNS'), (SELECT id FROM knowledge.condition WHERE condition_code = 'PNEUMONIA'), 1.0),
   ('52a15f30-40f7-54f0-ad9d-ad2c7cd96d9c', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-KENYA-TREATMENT-COMPLIANCE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'PNEUMONIA'), 1.0),
   ('fefe4a2d-c864-5f0c-b945-7a1e967ff625', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-KENYA-RETURN-CARE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'PNEUMONIA'), 1.0)  ON CONFLICT DO NOTHING;

-- drug_dose_reference (JUR-KENYA amoxicillin 40-45 mg/kg)
INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, jurisdiction_code, verification_status) VALUES
   ('a46894ef-bb85-5f53-a079-4a5f6048a75b', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-AMOXICILLIN'), 'paediatric', 'PNEUMONIA', 'oral', '40-45 mg/kg/dose high-dose amoxicillin dispersible tablets (non-severe pneumonia, 5 days) - Kenya BPP 5th ed p46', 'every 12 hours', '5 days', 'Kenya BPP 5th ed p46', true, 'mg_per_kg', 40, 45, 'JUR-KENYA', 'verified')
  ON CONFLICT DO NOTHING;

-- governance.knowledge_object
INSERT INTO governance.knowledge_object (id, object_code, knowledge_type, canonical_name, description, source_claim_code, jurisdiction_code, population_code, evidence_level_code, lifecycle_status, confidence, is_active, status) VALUES
   ('1e31a691-0f97-5638-9b43-3b55deb2bbd6', 'PROT-PNEUMONIA-KENYA-PAED', 'PROTOCOL', 'Kenya paediatric pneumonia management pathway (5th ed)', 'Jurisdictional overlay for JUR-KENYA of the paediatric pneumonia management pathway: eligibility (2-59mo), danger-sign assessment, severe vs non-severe classification, investigation, severe (parenteral + refer) vs non-severe (high-dose amoxicillin 40-45 mg/kg/dose) treatment, 48h review and escalation, monitoring and caregiver education, follow-up. Replaces the generic protocol for Kenyan children.', 'BPP-0002', 'JUR-KENYA', 'POP-PAEDIATRIC', 'EV-B', 'ACTIVE', 0.95, true, 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO governance.knowledge_object_version (id, object_id, version_no, version_code, change_note, lifecycle_status, source_claim_code, created_by) VALUES
   ('db2b66db-a56e-5bc4-b580-24571ff42891', (SELECT id FROM governance.knowledge_object WHERE object_code = 'PROT-PNEUMONIA-KENYA-PAED'), 1, 'GO-V-R8-PNEUMONIA-PAED-1', 'R8 Kenya paediatric pneumonia overlay (BPP-0001..0005).', 'ACTIVE', 'BPP-0002', 'Dr A Otieno')
  ON CONFLICT DO NOTHING;

-- provenance
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES
   ('a76013e4-f491-57c0-9657-868398cfda0a', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'BPP-0002'), 'PROTOCOL', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-PNEUMONIA-KENYA-PAED'), 'PROT-PNEUMONIA-KENYA-PAED', 'derived_from')  ON CONFLICT DO NOTHING;

-- Done
SELECT 'R8 Kenya pneumonia overlay seed applied successfully';
