-- =============================================================================
-- AMEXAN Medical Knowledge Compiler - R6 COPD pathway (adult)
-- Chronic + exacerbation COPD grounded to Kumar & Clark 10e p955-960
-- (claims KCR-0013..KCR-0018). Adds GOLD severity, drug therapy, LTOT, NIV.
-- GENERATED FILE - do not edit by hand. Regenerate with:
--   python knowledge-compiler/build_r6_copd.py <out>
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. knowledge.source_claim - COPD claims (Kumar & Clark p955-960)
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.source_claim (claim_id, claim_code, source_version_id, chapter_id, chunk_id, page_start, page_end, claim_type, claim_kind, claim_text, knowledge_type, contract, confidence, status) VALUES
   ('bb6b2dac-fb97-5cde-a274-f7ab4d66f609', 'KCR-0013', 'KUMAR_CLARK_10_2017', 'KC-C28', 'd133e703-46c8-5a26-a05b-0bd6c507b385', '955', '955', 'RESPIRATORY_METHOD', 'threshold', 'COPD is airflow limitation that is not fully reversible, usually progressive, and associated with an abnormal inflammatory response of the lungs to noxious particles or gases. It brings together emphysema, small airways disease and chronic bronchitis. Chronic bronchitis is classically a daily productive cough for 3 months per year for 2 consecutive years. Cigarette smoking accounts for over 90% of cases in developed countries; in developing countries, smoke from biomass heating fuels and cooking in poorly ventilated areas is implicated.', 'medicine', '{"what_is_it":"COPD definition + chronic bronchitis + aetiology","what_fact_produces":"COUGH_DURATION_DAYS, SMOKING_STATUS, SMOKING_PACK_YEARS, BIOMASS_EXPOSURE","source_support":"Kumar & Clark 10e p955"}'::jsonb, 0.9, 'VERIFIED'),
   ('1d246dc5-8a7d-5c36-bb06-8f4aff8e2cbd', 'KCR-0014', 'KUMAR_CLARK_10_2017', 'KC-C28', 'd133e703-46c8-5a26-a05b-0bd6c507b385', '956', '956', 'RESPIRATORY_METHOD', 'rule', 'Characteristic symptoms of COPD: productive cough with white or clear sputum, wheeze and breathlessness; patients are prone to lower respiratory tract infections. Systemic effects include hypertension, osteoporosis, depression, weight loss, reduced muscle mass, weakness and right heart failure. In severe disease the patient is tachypnoeic with prolonged expiration, uses accessory muscles, may have intercostal indrawing and pursing of the lips on expiration; chest expansion is poor, lungs hyperinflated, cricosternal distance reduced, with loss of normal cardiac and liver dullness. Hypercapnia causes peripheral vasodilation, bounding pulse, coarse flapping tremor, confusion and progressive drowsiness.', 'medicine', '{"what_is_it":"COPD clinical features + signs","what_fact_produces":"PURSED_LIPS, COUGH_PRODUCTIVITY, DYSPNOEA_PRESENT, RESP_RATE","source_support":"Kumar & Clark 10e p956"}'::jsonb, 0.9, 'VERIFIED'),
   ('b0c3d2f8-69e7-512b-bcd1-7aa73f64b94e', 'KCR-0015', 'KUMAR_CLARK_10_2017', 'KC-C28', 'd133e703-46c8-5a26-a05b-0bd6c507b385', '957', '957', 'RESPIRATORY_METHOD', 'investigation', 'COPD diagnosis is usually clinical: history of breathlessness and sputum production in a chronic smoker. Spirometry shows airflow limitation (FEV1:FVC reduced, PEFR low; usually <15% reversibility). CXR is often normal even when advanced, but classic features are over-inflation with low flat diaphragms and sometimes bullae with pruned vessels. Hb and packed cell volume may be elevated from persistent hypoxaemia (secondary polycythaemia). Blood gases determine respiratory failure. Sputum may grow Strep. pneumoniae, H. influenzae and Moraxella catarrhalis. ECG may show P pulmonale, RBBB and right ventricular hypertrophy. Measure alpha1-antitrypsin in premature disease or lifelong non-smokers.', 'medicine', '{"what_is_it":"COPD diagnosis + investigations","what_connects_to":"INV-SPIROMETRY, INV-ABG, INV-CXR, INV-FBC","source_support":"Kumar & Clark 10e p957"}'::jsonb, 0.9, 'VERIFIED'),
   ('d0a30235-d0cc-5a3a-b8ba-0c06f2014d99', 'KCR-0016', 'KUMAR_CLARK_10_2017', 'KC-C28', 'd133e703-46c8-5a26-a05b-0bd6c507b385', '957', '957', 'RESPIRATORY_METHOD', 'threshold', 'COPD airflow limitation severity (post-bronchodilator FEV1 in patients with FEV1/FVC <0.70): GOLD 1 Mild FEV1 >=80% predicted; GOLD 2 Moderate 50% <= FEV1 <80%; GOLD 3 Severe 30% <= FEV1 <50%; GOLD 4 Very severe FEV1 <30% predicted.', 'medicine', '{"what_is_it":"GOLD severity classification","what_fact_produces":"FEV1_PERCENT, FEV1_FVC_RATIO","source_support":"Kumar & Clark 10e p957 (GOLD 2016)"}'::jsonb, 0.9, 'VERIFIED'),
   ('da13744a-e1b5-51b6-9371-d2587ead8046', 'KCR-0017', 'KUMAR_CLARK_10_2017', 'KC-C28', 'd133e703-46c8-5a26-a05b-0bd6c507b385', '957', '957', 'RESPIRATORY_METHOD', 'management', 'COPD management: smoking cessation is the single most useful measure. Drug therapy: mild COPD responds to inhaled short-acting beta-2 agonist (salbutamol 200 mcg every 4-6 h); moderate/severe uses a long-acting beta-2 agonist; a regular LAMA (tiotropium) improves lung function, dyspnoea and quality of life; inhaled corticosteroids are recommended with frequent exacerbations or FEV1 <50% predicted (high-dose ICS not advised - pneumonia risk); oral corticosteroids in acute exacerbation. Prompt antibiotics shorten exacerbations and should always be given in acute episodes; home antibiotics when sputum turns yellow/green; long-term azithromycin reduces exacerbations. Mucolytics (carbocysteine) reduce sputum viscosity and exacerbations. LTOT (>=15-19 h/day) improves survival when PaO2 <7.3 kPa on air on two occasions, or PaO2 <8 kPa with secondary polycythaemia, nocturnal hypoxaemia, peripheral oedema or pulmonary hypertension. Pulmonary rehabilitation improves fatigue, dyspnoea and exercise tolerance. Pneumococcal polysaccharide vaccine once + annual influenza vaccination.', 'medicine', '{"what_is_it":"COPD drug + non-drug management","what_connects_to":"medications, LTOT, rehabilitation, vaccination","source_support":"Kumar & Clark 10e p957-958"}'::jsonb, 0.9, 'VERIFIED'),
   ('693cdfe1-9fe7-54e5-a3ee-4671a6fd1be5', 'KCR-0018', 'KUMAR_CLARK_10_2017', 'KC-C28', 'd133e703-46c8-5a26-a05b-0bd6c507b385', '959', '959', 'RESPIRATORY_METHOD', 'management', 'Acute COPD exacerbation may be precipitated by viral or bacterial infection with cough, acute bronchospasm and dyspnoea, and Type I or Type II respiratory failure. Management: assess airway, breathing and circulation; controlled oxygen via Venturi mask (initially 24%, target saturation 88-92% for those at risk of hypercapnia) with close ABG monitoring; corticosteroids, antibiotics and bronchodilators (nebulized salbutamol and ipratropium) in the acute phase; chest physiotherapy to clear retained secretions. If respiratory acidosis persists (pH <7.35 with elevated PaCO2), consider non-invasive ventilation - NIV reduces the need for intubation and lowers mortality. CXR excludes pneumothorax (chest drain) or pneumonia (antibiotics).', 'medicine', '{"what_is_it":"acute COPD exacerbation management algorithm","what_connects_to":"protocol step (acute COPD)","source_support":"Kumar & Clark 10e p959-960"}'::jsonb, 0.9, 'VERIFIED')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 1. knowledge.condition - COPD + COPD exacerbation
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.condition (id, concept_id, condition_code, canonical_name, description, condition_type, status) VALUES
   ('3243e22c-36ed-5b10-bf53-9d725910d14b', NULL, 'COND-COPD', 'COPD (chronic obstructive pulmonary disease)', 'Chronic airflow limitation that is not fully reversible, encompassing emphysema, small airways disease and chronic bronchitis; caused by long-term exposure to toxic particles (smoking, biomass smoke).', 'chronic', 'active'),
   ('9714d3b6-126a-58c3-8be9-f040506c4d71', NULL, 'COND-COPD-EXACERBATION', 'COPD exacerbation', 'Acute worsening of COPD with increased dyspnoea, cough and sputum, precipitated by viral or bacterial infection; may cause Type I or Type II respiratory failure.', 'acute', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.phenotype_differential (id, phenotype_id, condition_id, relationship_type, weight) VALUES
   ('53bcf204-e74a-50a7-8311-e9a8bed9fc59', (SELECT id FROM knowledge.phenotype WHERE phenotype_code = 'PHEN-CHRONIC-PRODUCTIVE-COUGH'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 'associated', '0.80'),
   ('ca24dab4-7192-5c63-ad1a-9fc45a6f3659', (SELECT id FROM knowledge.phenotype WHERE phenotype_code = 'PHEN-AIRWAY-WHEEZE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 'associated', '0.60'),
   ('0e10bc09-631f-52fb-80a4-4c6b89999572', (SELECT id FROM knowledge.phenotype WHERE phenotype_code = 'PHEN-ACUTE-HYPOXAEMIC'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 'associated', '0.70'),
   ('13db522c-6cb3-5f2f-9508-e24c59725664', (SELECT id FROM knowledge.phenotype WHERE phenotype_code = 'PHEN-RESPIRATORY-FAILURE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 'associated', '0.80'),
   ('c067ee62-b7db-5d60-92b9-60ceee1c5d3c', (SELECT id FROM knowledge.phenotype WHERE phenotype_code = 'PHEN-ACUTE-LRTI'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 'associated', '0.40')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. clinical.fact_definition - FEV1_PERCENT, PURSED_LIPS
-- ---------------------------------------------------------------------------
INSERT INTO clinical.fact_definition (code, name, description, data_type, allow_multiple, is_active) VALUES
   ('FEV1_PERCENT', 'FEV1_PERCENT', 'Forced expiratory volume in 1 second (% predicted) - GOLD severity grade', 'numeric', false, true),
   ('PURSED_LIPS', 'PURSED_LIPS', 'Pursing of the lips on expiration - sign of severe COPD / emphysema', 'coded', false, true)
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2b. knowledge.severity_score - SCORE-GOLD (GOLD 1-4 by FEV1 %)
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.severity_score (id, score_code, canonical_name, description, condition_id, population, max_score, source_reference, status) VALUES
   ('2583d638-50b6-5dac-8f3a-6cf46bc47228', 'SCORE-GOLD', 'GOLD airflow limitation severity', 'GOLD 1-4 severity based on post-bronchodilator FEV1 % predicted with FEV1/FVC <0.70 (KCR-0016).', (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 'adult', 4, 'Kumar & Clark 10e p957 (GOLD 2016) - KCR-0016', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.severity_score_component (id, score_id, component_code, component_name, condition, points, rationale, sort_order) VALUES
   ('6c4dcaae-7577-5758-90d2-169f1ab765e9', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-GOLD'), 'GOLD-1', 'GOLD 1 - Mild (FEV1 >=80% predicted)', '{"type":"and","conditions":[{"type":"numeric_lt","fact_code":"FEV1_FVC_RATIO","threshold":0.7},{"type":"numeric_gte","fact_code":"FEV1_PERCENT","threshold":80}]}'::jsonb, '1', 'Post-bronchodilator FEV1 >=80% predicted with FEV1/FVC <0.70 (KCR-0016).', '10'),
   ('be1f5d48-3fae-5fd4-ab4a-c64c24ae66ad', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-GOLD'), 'GOLD-2', 'GOLD 2 - Moderate (50% <= FEV1 <80%)', '{"type":"and","conditions":[{"type":"numeric_lt","fact_code":"FEV1_FVC_RATIO","threshold":0.7},{"type":"numeric_gte","fact_code":"FEV1_PERCENT","threshold":50},{"type":"numeric_lt","fact_code":"FEV1_PERCENT","threshold":80}]}'::jsonb, '2', 'Post-bronchodilator FEV1 50-79% predicted with FEV1/FVC <0.70 (KCR-0016).', '11'),
   ('9f1bd192-f195-5d22-a8d4-7e628ab0b7c2', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-GOLD'), 'GOLD-3', 'GOLD 3 - Severe (30% <= FEV1 <50%)', '{"type":"and","conditions":[{"type":"numeric_lt","fact_code":"FEV1_FVC_RATIO","threshold":0.7},{"type":"numeric_gte","fact_code":"FEV1_PERCENT","threshold":30},{"type":"numeric_lt","fact_code":"FEV1_PERCENT","threshold":50}]}'::jsonb, '3', 'Post-bronchodilator FEV1 30-49% predicted with FEV1/FVC <0.70 (KCR-0016).', '12'),
   ('64fdb787-35eb-5333-82f6-51ff43e15cf1', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-GOLD'), 'GOLD-4', 'GOLD 4 - Very severe (FEV1 <30%)', '{"type":"and","conditions":[{"type":"numeric_lt","fact_code":"FEV1_FVC_RATIO","threshold":0.7},{"type":"numeric_lt","fact_code":"FEV1_PERCENT","threshold":30}]}'::jsonb, '4', 'Post-bronchodilator FEV1 <30% predicted with FEV1/FVC <0.70 (KCR-0016).', '13')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.severity_score_interpretation (id, score_id, min_score, max_score, severity_label, disposition, recommendation) VALUES
   ('bf015a9a-ca43-5165-9265-0db7ba86af2a', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-GOLD'), '1', '1', 'GOLD 1 - Mild', 'Outpatient', 'Post-bronchodilator FEV1 >=80% predicted; short-acting bronchodilator for symptoms; annual influenza + single pneumococcal vaccine.'),
   ('d7dbc3dd-61d5-59cb-8c1e-218e645fbe4b', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-GOLD'), '2', '2', 'GOLD 2 - Moderate', 'Outpatient', 'Post-bronchodilator FEV1 50-79%; add LABA/LAMA; consider ICS if frequent exacerbations or blood eosinophilia.'),
   ('da87b435-dd14-5f31-b5ad-df58613065a0', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-GOLD'), '3', '3', 'GOLD 3 - Severe', 'Outpatient', 'Post-bronchodilator FEV1 30-49%; LABA + LAMA; ICS for exacerbations; pulmonary rehabilitation.'),
   ('2049fa81-1a06-574b-8603-0d18217f5cc6', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-GOLD'), '4', '4', 'GOLD 4 - Very severe', 'Refer', 'Post-bronchodilator FEV1 <30%; assess LTOT, pulmonary rehabilitation, surgical/transplant options; screen for respiratory failure.')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. knowledge.medication - COPD armamentarium
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.concept (id, concept_code, concept_type, canonical_name, display_name, status) VALUES
   ('21e86c61-d3c4-5b9a-b1dc-7ae7f1d0f58c', 'CNS-MED-TIOTROPIUM', 'medication', 'Tiotropium bromide', 'Tiotropium bromide', 'active'),
   ('ce43dbd2-4e76-547f-9486-71d8ed9cfc7c', 'CNS-MED-SALMETEROL', 'medication', 'Salmeterol', 'Salmeterol', 'active'),
   ('ec1a4821-93b4-50a9-a499-bd4abcdbf641', 'CNS-MED-ROFLUMILAST', 'medication', 'Roflumilast', 'Roflumilast', 'active'),
   ('845a2296-dbf7-5d6a-9ae0-2703f7eb4e33', 'CNS-MED-CARBOCYSTEINE', 'medication', 'Carbocysteine', 'Carbocysteine', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.medication (id, concept_id, medication_code, generic_name, drug_class, route_options, formulations, contraindications, evidence_source, status) VALUES
   ('32ca3a31-b4de-5298-8c3e-99958a42d949', '21e86c61-d3c4-5b9a-b1dc-7ae7f1d0f58c', 'MED-TIOTROPIUM', 'Tiotropium bromide', 'Long-acting muscarinic antagonist (LAMA)', '["inhalation"]'::jsonb, '["dry powder inhaler 18 mcg"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Kumar & Clark 10e p957-958 (KCR-0017) - verify against local formulary.', 'active'),
   ('a600caf6-1821-5b33-81d8-913c3fea425c', 'ce43dbd2-4e76-547f-9486-71d8ed9cfc7c', 'MED-SALMETEROL', 'Salmeterol', 'Long-acting beta-2 agonist (LABA)', '["inhalation"]'::jsonb, '["MDI 25 mcg/puff"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Kumar & Clark 10e p957-958 (KCR-0017) - verify against local formulary.', 'active'),
   ('80165a86-fe38-5462-a55d-270453e259b5', 'ec1a4821-93b4-50a9-a499-bd4abcdbf641', 'MED-ROFLUMILAST', 'Roflumilast', 'Phosphodiesterase type 4 (PDE4) inhibitor', '["oral"]'::jsonb, '["tablet 500 mcg"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Kumar & Clark 10e p957-958 (KCR-0017) - verify against local formulary.', 'active'),
   ('41f90c8c-d47c-56f3-8968-57b2f2d69856', '845a2296-dbf7-5d6a-9ae0-2703f7eb4e33', 'MED-CARBOCYSTEINE', 'Carbocysteine', 'Mucolytic', '["oral"]'::jsonb, '["capsule 375 mg","suspension 250 mg/5ml"]'::jsonb, '["serious immediate allergy to this class"]'::jsonb, 'Kumar & Clark 10e p957-958 (KCR-0017) - verify against local formulary.', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('96bb7b80-45e4-5f44-a07a-6d374f6d30e3', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-SALBUTAMOL'), 'adult', 'COND-COPD', 'inhalation', '200 mcg by inhaler for acute symptom relief (mild COPD); in exacerbation 2.5-5 mg by nebulizer', 'every 4-6 h as needed (exacerbation: up to 3 nebulizations in first hour)', 'during exacerbation', 'Kumar & Clark 10e p955-960 (KCR-0017)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('00cb8e8f-d4aa-5791-a906-1879cda6d78d', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0017'), 'drug_dose_reference', '96bb7b80-45e4-5f44-a07a-6d374f6d30e3', 'DOSE:MED-SALBUTAMOL', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('bf6b855b-eb37-52b3-89a7-c28ad1e2e178', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-SALBUTAMOL'), 'adult', 'COND-COPD-EXACERBATION', 'inhalation', '2.5-5 mg by nebulizer during acute exacerbation', 'up to 3 treatments in 1 hour, then as needed', 'during exacerbation', 'Kumar & Clark 10e p955-960 (KCR-0018)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('3ddfa5f6-a3dd-5eb0-9da6-7ac38446b9be', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0018'), 'drug_dose_reference', 'bf6b855b-eb37-52b3-89a7-c28ad1e2e178', 'DOSE:MED-SALBUTAMOL', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('fc450fb3-58f5-54d9-bb36-e6aed83ce77f', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-IPRATROPIUM'), 'adult', 'COND-COPD-EXACERBATION', 'inhalation', '250-500 mcg by nebulizer during acute exacerbation', 'every 20 min in first hour, then as needed', 'during exacerbation', 'Kumar & Clark 10e p955-960 (KCR-0018)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('725903a8-0b9d-5a5b-bc56-3afb5868692d', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0018'), 'drug_dose_reference', 'fc450fb3-58f5-54d9-bb36-e6aed83ce77f', 'DOSE:MED-IPRATROPIUM', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('ee1f857b-cc49-526a-955f-c524d0dd0649', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-PREDNISOLONE'), 'adult', 'COND-COPD-EXACERBATION', 'oral', '30-40 mg oral once daily', 'once daily', '7-14 days (short course)', 'Kumar & Clark 10e p955-960 (KCR-0017)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('2a5fba09-b22b-51bf-bf22-0c2e7b0f6a94', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0017'), 'drug_dose_reference', 'ee1f857b-cc49-526a-955f-c524d0dd0649', 'DOSE:MED-PREDNISOLONE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('80bad8a8-5d9a-5dc0-9e5a-b45940b6650a', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-TIOTROPIUM'), 'adult', 'COND-COPD', 'inhalation', '18 mcg inhaled once daily (LAMA)', 'once daily', 'ongoing', 'Kumar & Clark 10e p955-960 (KCR-0017)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('d7249e27-a655-5e9a-955b-572c7b0b4791', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0017'), 'drug_dose_reference', '80bad8a8-5d9a-5dc0-9e5a-b45940b6650a', 'DOSE:MED-TIOTROPIUM', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('819791ee-68aa-5cec-a39d-0b3bb3c29ec1', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-SALMETEROL'), 'adult', 'COND-COPD', 'inhalation', '50 mcg inhaled twice daily (LABA)', 'twice daily', 'ongoing', 'Kumar & Clark 10e p955-960 (KCR-0017)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('16e5e6a8-d6f9-59d6-8775-d2c19aaa07b5', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0017'), 'drug_dose_reference', '819791ee-68aa-5cec-a39d-0b3bb3c29ec1', 'DOSE:MED-SALMETEROL', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('c05620a4-7303-5328-89d7-c58c27810d4f', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-ROFLUMILAST'), 'adult', 'COND-COPD', 'oral', '500 mcg oral once daily (PDE4 inhibitor, FEV1 <50% + chronic bronchitis)', 'once daily', 'ongoing', 'Kumar & Clark 10e p955-960 (KCR-0017)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('d55f9754-9653-5381-8431-ad497f93dc2d', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0017'), 'drug_dose_reference', 'c05620a4-7303-5328-89d7-c58c27810d4f', 'DOSE:MED-ROFLUMILAST', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('8b7c8f5a-01cf-5805-b0a2-8aef0ea52cac', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-CARBOCYSTEINE'), 'adult', 'COND-COPD', 'oral', '750 mg oral three times daily (mucolytic)', 'three times daily', 'during exacerbations / as maintenance', 'Kumar & Clark 10e p955-960 (KCR-0017)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('1800c39b-38a0-5361-90ed-a485e5d2dd6d', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0017'), 'drug_dose_reference', '8b7c8f5a-01cf-5805-b0a2-8aef0ea52cac', 'DOSE:MED-CARBOCYSTEINE', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.drug_dose_reference (id, medication_id, population, indication_code, route, dose_expression, frequency_expression, duration_expression, evidence_source, is_verified, weight_basis, dose_per_kg_min, dose_per_kg_max, verification_status) VALUES
   ('90598026-ba65-5977-a309-88d43dcc66b2', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-AZITHROMYCIN'), 'adult', 'COND-COPD', 'oral', 'Long-term macrolide 250-500 mg to reduce frequent exacerbations', '250 mg daily or 500 mg three times weekly', 'ongoing for frequent exacerbations', 'Kumar & Clark 10e p955-960 (KCR-0017)', TRUE, NULL, NULL, NULL, 'verified')
  ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('2273a2df-ba52-5857-bd81-1b0bc607efc0', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0017'), 'drug_dose_reference', '90598026-ba65-5977-a309-88d43dcc66b2', 'DOSE:MED-AZITHROMYCIN', 'derived_from')   ON CONFLICT DO NOTHING;

INSERT INTO knowledge.medication_condition (id, medication_id, condition_id, role, weight) VALUES
   ('d7c8ecfe-7ada-5a63-ae52-03da4b2817a0', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-SALBUTAMOL'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 'treatment', '0.90'),
   ('99766cb2-d8ae-581e-93f2-147272693261', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-TIOTROPIUM'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 'treatment', '0.90'),
   ('88ae1f21-caa7-5b4d-8adc-f460bb19c21d', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-SALMETEROL'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 'treatment', '0.80'),
   ('41c03275-47dc-5fcd-a0dd-0215337760d8', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-ROFLUMILAST'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 'treatment', '0.50'),
   ('949ab8ed-1c5e-5c84-85eb-396bc670201f', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-CARBOCYSTEINE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 'supportive', '0.60'),
   ('f7f2ea53-5ae0-5639-b998-2bb99e1d82a6', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-AZITHROMYCIN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 'treatment', '0.50'),
   ('14cc1201-a6c3-5d7e-9afb-3292696ca90b', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-SALBUTAMOL'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 'treatment', '1.00'),
   ('4ae3c7bf-a76f-5673-9d94-510baa964da7', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-IPRATROPIUM'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 'treatment', '0.90'),
   ('681b55be-6c43-51d7-8617-e5b59ced0a59', (SELECT id FROM knowledge.medication WHERE medication_code = 'MED-PREDNISOLONE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 'treatment', '0.90')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. knowledge.investigation - spirometry + ABG
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.investigation (id, concept_id, investigation_code, canonical_name, description, investigation_type, body_system_code, specimen, turn_around_minutes, preparation, status) VALUES
   ('3076fac0-f577-5ceb-a269-63818b8890a7', NULL, 'INV-SPIROMETRY', 'Spirometry (lung function tests)', 'Measures FEV1, FVC and PEFR to confirm airflow limitation and grade GOLD severity.', 'physiological', 'RESPIRATORY', NULL, NULL, NULL, 'active'),
   ('94aa6ea3-a8c9-5b44-99c9-0a6eb1980a6e', NULL, 'INV-ABG', 'Arterial blood gas', 'Determines PaO2, PaCO2 and pH to classify Type I/II respiratory failure and guide controlled oxygen / NIV.', 'laboratory', 'RESPIRATORY', NULL, NULL, NULL, 'active')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 5. PROT-COPD-EXACERBATION - full 12-step pathway (adult)
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.protocol (id, concept_id, protocol_code, canonical_name, version_label, description, specialty_code, purpose, status, is_guideline, source_reference, population) VALUES
   ('1e6d0e50-1ae0-5a47-803b-05cfdef6dcc5', NULL, 'PROT-COPD-EXACERBATION', 'Acute COPD exacerbation pathway', '1.0', 'Adult acute COPD exacerbation: ABC, controlled oxygen 88-92%, ABG, bronchodilators + corticosteroids + antibiotics, clearance, CXR, NIV escalation, critical care, discharge prevention.', 'pulmonology', 'management', 'active', true, 'Kumar & Clark 10e p955-960 (KCR-0013..0018)', 'adult')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_condition (id, protocol_id, condition_id, is_primary) VALUES
   ('30f3e5bf-d55e-5837-9091-ff14792bd96e', '1e6d0e50-1ae0-5a47-803b-05cfdef6dcc5', (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), true)
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_step (id, protocol_id, step_code, step_label, step_type, sequence_no, instruction, rationale, required) VALUES
   ('951e0ac5-054f-5adc-8219-823ca588094c', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-01', 'Confirm acute COPD exacerbation', 'eligibility', '10', 'Confirm known COPD with an acute, sustained worsening of dyspnoea, cough or sputum beyond day-to-day variation.', 'Exacerbation is precipitated by viral/bacterial infection and may progress to respiratory failure (KCR-0018).', TRUE),
   ('511f62d2-8bfc-54f5-b659-add2dafb62d7', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-02', 'Assess airway, breathing and circulation', 'red_flag', '20', 'Rapid ABC assessment; detect severe distress, confusion, drowsiness, bounding pulse or flapping tremor (hypercapnia), cyanosis or cardiorespiratory arrest.', 'Airway compromise and cardiorespiratory arrest require immediate resuscitation (KCR-0018).', TRUE),
   ('3fa683a8-c69f-5e76-b4b5-7c2726ea2a01', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-03', 'Deliver controlled oxygen therapy', 'treatment', '30', 'For those at risk of hypercapnic failure use a Venturi mask (start 24%, titrate) to maintain target saturation 88-92%; monitor closely.', 'Excess oxygen in Type II failure suppresses hypoxic drive and raises PaCO2 (KCR-0018).', TRUE),
   ('f3af4211-f2cd-5111-b02c-7dbb1e034c92', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-04', 'Obtain arterial blood gas', 'investigation', '40', 'Measure ABG to classify Type I (PaO2 <8 kPa, normal/low PaCO2) vs Type II (PaO2 <8 kPa, PaCO2 >6.5 kPa) respiratory failure; check pH.', 'Respiratory acidosis (pH <7.35 with raised PaCO2) despite medical management triggers NIV consideration (KCR-0018).', TRUE),
   ('d703cf02-e945-5856-b70d-654555ddb6f7', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-05', 'Start bronchodilators + corticosteroids + antibiotics', 'treatment', '50', 'Nebulized salbutamol and ipratropium; oral prednisolone 30-40 mg; prompt antibiotics (shorten exacerbation, prevent admission); home antibiotics when sputum turns yellow/green.', 'Triple therapy in the acute phase shortens the exacerbation; ICS long-term decisions wait until recovery (KCR-0017/0018).', TRUE),
   ('55478fc6-d933-5888-bedd-01ca0df77f83', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-06', 'Clear retained secretions', 'treatment', '60', 'Encourage effective cough; chest physiotherapy when clearing secretions is difficult.', 'Retained secretions worsen obstruction and gas exchange (KCR-0018).', TRUE),
   ('b1e45542-6627-55f8-88a8-7601ee5e1743', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-07', 'Image the chest', 'investigation', '70', 'CXR to exclude pneumothorax (chest drain; CT guidance if complex bullous disease) and pneumonia (antibiotics).', 'Pneumothorax and pneumonia are treatable precipitants of deterioration (KCR-0018).', TRUE),
   ('547fab8b-d9a5-55df-a598-6096fec88a32', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-08', 'Re-assess and repeat ABG', 'monitoring', '80', 'Repeat ABG at 30-60 min (or on increasing oxygen requirements/breathlessness); keep target saturation 88-92%.', 'Trends in pH/PaCO2 determine escalation to NIV (KCR-0018).', TRUE),
   ('6ef05aa4-4f5c-5010-8017-bdbd0c7f239a', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-09', 'Consider non-invasive ventilation', 'escalation', '90', 'If persistent respiratory acidosis (pH <7.35 with PaCO2 >6.5 kPa) despite medical management and clinically appropriate: start NIV; refer to senior; review and discuss ceiling of care.', 'NIV reduces the need for intubation and lowers mortality in decompensated Type II failure (KCR-0018).', TRUE),
   ('4e91092a-e774-5772-8fd7-6ebe39ed1077', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-10', 'Escalate to critical care if deteriorating', 'escalation', '100', 'If deterioration despite NIV and clinically appropriate: consider invasive ventilation; reassess ceiling of care.', 'Invasive ventilation is used only with a clear precipitating factor and reasonable overall prognosis (KCR-0018).', TRUE),
   ('6505711b-7d53-5ff1-8d5e-f10b481f0aa5', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-11', 'Plan discharge and prevention', 'education', '110', 'Smoking cessation (single most useful measure); pneumococcal vaccine + annual influenza; pulmonary rehabilitation; assess LTOT if PaO2 <7.3 kPa (or <8 kPa with polycythaemia/nocturnal hypoxaemia/oedema/pulmonary hypertension).', 'Prevention and rehabilitation improve outcomes and reduce exacerbation frequency (KCR-0017/0018).', TRUE),
   ('df125acd-419b-5620-901f-6a94552df7a4', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), 'STEP-12', 'Close the care loop', 'follow_up', '120', 'Grade GOLD severity (FEV1/FVC <0.70; FEV1 % predicted), document treatment, response, LTOT/referral plan and follow-up; consider BODE for prognosis.', 'COPD is chronic: the exacerbation episode feeds into ongoing maintenance and surveillance (KCR-0015/0016).', TRUE)
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_action (id, protocol_id, step_id, action_type, action_code, action_name, detail, urgency, sort_order) VALUES
   ('8fe5ff50-e0f8-57d7-9089-39f850503c68', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-01'), 'score', 'SCORE-GOLD', 'GOLD severity grade', 'Grade airflow limitation by post-bronchodilator FEV1 (% predicted) with FEV1/FVC <0.70', 'routine', '10'),
   ('fa13f7a9-5b22-52d7-80fc-4cabf5628977', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-SPO2', 'Oxygen saturation monitoring', 'Target 88-92% for hypercapnia risk', 'immediate', '10'),
   ('8135719c-2845-5bbf-b40c-2486ff4328f0', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-RR', 'Respiratory rate monitoring', 'Tachypnoea and work of breathing', 'immediate', '20'),
   ('c55e35d9-e975-5f1c-9554-10554c924597', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-03'), 'advice', 'ADV-COPD-TARGETED-O2', 'Controlled oxygen (target 88-92%)', 'Venturi mask, start 24%, titrate to target SpO2 88-92%; avoid excess oxygen (hypercapnia risk)', 'immediate', '10'),
   ('51396718-60a9-5f25-9adf-52f2a86716ff', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-04'), 'investigate', 'INV-ABG', 'Arterial blood gas', 'Classify Type I/II respiratory failure; pH trend', 'urgent', '10'),
   ('2e3d3f42-8ae7-5120-82bc-912b36531781', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-05'), 'medicate', 'MED-SALBUTAMOL', 'Salbutamol (SABA)', 'Nebulizer 2.5-5 mg in exacerbation', 'immediate', '10'),
   ('2d4fd947-adc1-5567-ad7c-6c3e370df2a8', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-05'), 'medicate', 'MED-IPRATROPIUM', 'Ipratropium (SAMA)', 'Nebulizer 250-500 mcg in exacerbation', 'immediate', '20'),
   ('ef656b0b-c05e-5c94-95a5-491e40debdbd', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-05'), 'medicate', 'MED-PREDNISOLONE', 'Prednisolone', '30-40 mg oral once daily 7-14 days', 'urgent', '30'),
   ('97b354f0-a39c-55c5-8b60-54deda60afc3', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-05'), 'medicate', 'MED-AMOXICILLIN', 'Antibiotic (amoxicillin)', 'Prompt antibiotics for acute episode; home antibiotics when sputum turns yellow/green', 'urgent', '40'),
   ('f89f3b00-d932-572f-a121-6899baed2c38', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-06'), 'advice', 'ADV-COPD-CLEARANCE', 'Secretions clearance', 'Effective cough + chest physiotherapy', 'urgent', '10'),
   ('95abb61c-897f-50ab-94fa-44cb255eb206', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-07'), 'investigate', 'INV-CXR', 'Chest X-ray', 'Exclude pneumothorax and pneumonia', 'urgent', '10'),
   ('b7ae4d22-bab0-5f69-894c-d79d56399951', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-08'), 'monitor', 'MON-SPO2', 'Oxygen saturation monitoring', 'Maintain target 88-92%; repeat ABG at 30-60 min', 'urgent', '10'),
   ('60b9938b-7643-56d2-890e-e2ccd4d044c7', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-08'), 'investigate', 'INV-ABG', 'Arterial blood gas (repeat)', 'Repeat 30-60 min or on deterioration', 'urgent', '20'),
   ('ec59af81-a3e1-5fc9-b94a-cb853bb3dfbd', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-09'), 'refer', 'REF-NIV', 'Non-invasive ventilation', 'pH <7.35 with PaCO2 >6.5 kPa despite medical management', 'immediate', '10'),
   ('b21ac7f6-7983-5c95-8562-36798423e37b', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-09'), 'advice', 'ADV-COPD-CEILING', 'Ceiling of care discussion', 'Review and discuss ceiling of care', 'urgent', '20'),
   ('fef06a06-4bc7-5c9b-9234-dbbe7220c4fb', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-10'), 'refer', 'REF-CRITICAL-CARE', 'Critical care referral', 'Invasive ventilation if deterioration despite NIV + appropriate', 'immediate', '10'),
   ('0c3c7176-47fb-564d-bd53-0fa6250b9a9a', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-COPD-SMOKING-CESSATION', 'Smoking cessation', 'Single most useful measure; includes biomass smoke reduction', 'routine', '10'),
   ('a28d1954-52d0-5608-aa37-d379a76fb2f4', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-COPD-PULMONARY-REHAB', 'Pulmonary rehabilitation', 'Improves dyspnoea, fatigue and exercise tolerance', 'routine', '20'),
   ('adf362f1-6467-52b1-a55e-67d3477d1768', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-COPD-VACCINES', 'Pneumococcal + influenza vaccination', 'Single pneumococcal vaccine + annual influenza', 'routine', '30'),
   ('dea4f21c-de05-5d36-b1f5-d751077b73e7', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-COPD-LTOT', 'Long-term oxygen therapy', 'Assess if PaO2 <7.3 kPa on air (or <8 kPa with polycythaemia/nocturnal hypoxaemia/oedema/pulmonary hypertension); 15-19 h/day', 'routine', '40'),
   ('980d49aa-c08d-5957-96f4-ddbe37f719ed', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-COPD-EXACERBATION' AND ps.step_code = 'STEP-12'), 'educate', 'EDU-COPD-CLINICIAN', 'COPD reasoning summary', 'Render GOLD grade, evidence, treatment/escalation rationale', 'routine', '10')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_monitoring (id, protocol_id, monitoring_id, frequency, deterioration_rule, escalation_instruction) VALUES
   ('62e43267-b6e3-5b8a-baff-9a0e0e0130d5', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-SPO2'), 'Continuous during exacerbation; target 88-92% if hypercapnia risk (Venturi)', 'SpO2 <88% despite oxygen, or oversaturation >92% with rising PaCO2', 'Check ABG; adjust oxygen; escalate to NIV if respiratory acidosis'),
   ('549ea62e-09b1-5895-a190-efc6f7fcdfb2', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-COPD-EXACERBATION'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-RR'), 'Continuous during exacerbation', 'Persistent tachypnoea or rising work of breathing', 'Reassess severity; consider ABG; escalate')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6. knowledge.education - COPD education objects
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.concept (id, concept_code, concept_type, canonical_name, display_name, status) VALUES
   ('a68b77d8-9922-5815-b29a-cffc0aafb7ca', 'CNS-EDU-COPD-SMOKING-CESSATION', 'education', 'Smoking cessation for COPD', 'Smoking cessation for COPD', 'active'),
   ('3b419d7f-9d58-57e6-8413-92c47fbb27ac', 'CNS-EDU-COPD-PULMONARY-REHAB', 'education', 'Pulmonary rehabilitation', 'Pulmonary rehabilitation', 'active'),
   ('ef9449fb-ed76-5f27-aea8-94a5fdda3c9c', 'CNS-EDU-COPD-VACCINES', 'education', 'Vaccination for COPD', 'Vaccination for COPD', 'active'),
   ('ef94c5b0-752e-5e85-8248-45ef86303506', 'CNS-EDU-COPD-LTOT', 'education', 'Long-term oxygen therapy', 'Long-term oxygen therapy', 'active'),
   ('95849528-80e1-568a-b48c-99ea3f16eae7', 'CNS-EDU-COPD-EXACERBATION-PLAN', 'education', 'COPD exacerbation action plan', 'COPD exacerbation action plan', 'active'),
   ('d4d34a47-4b0f-5afd-a6fe-6f13e391bfc3', 'CNS-EDU-COPD-CLINICIAN', 'education', 'COPD reasoning summary', 'COPD reasoning summary', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.education (id, concept_id, education_code, title, audience, content_type, language_code, literacy_level, body, status) VALUES
   ('edf388a1-d241-5a5b-b06b-25839579d655', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-COPD-SMOKING-CESSATION'), 'EDU-COPD-SMOKING-CESSATION', 'Smoking cessation for COPD', 'patient', 'instruction', 'en', 'plain', 'Smoking cessation is the single most useful measure in COPD; it slows deterioration. Reduce biomass smoke in the home. Seek support, nicotine replacement and follow-up (KCR-0017).', 'active'),
   ('31bb0c2b-f7a7-53f5-95d5-32b88e3c8567', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-COPD-PULMONARY-REHAB'), 'EDU-COPD-PULMONARY-REHAB', 'Pulmonary rehabilitation', 'patient', 'explanation', 'en', 'plain', 'Structured exercise and education improve fatigue, dyspnoea and exercise tolerance in COPD (KCR-0017).', 'active'),
   ('b3e17f20-ccd3-5add-9a5c-fdc1d4ea469b', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-COPD-VACCINES'), 'EDU-COPD-VACCINES', 'Vaccination for COPD', 'patient', 'instruction', 'en', 'plain', 'Receive a single pneumococcal polysaccharide vaccine and annual influenza vaccination (KCR-0017).', 'active'),
   ('8da5ce51-5922-51fc-a650-494c35a44242', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-COPD-LTOT'), 'EDU-COPD-LTOT', 'Long-term oxygen therapy', 'patient', 'explanation', 'en', 'plain', 'If PaO2 <7.3 kPa on air (or <8 kPa with polycythaemia/nocturnal hypoxaemia/peripheral oedema/pulmonary hypertension), LTOT for 15-19 h/day improves survival (KCR-0017).', 'active'),
   ('93d64f2e-e818-5205-8abe-9b9e07438eb4', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-COPD-EXACERBATION-PLAN'), 'EDU-COPD-EXACERBATION-PLAN', 'COPD exacerbation action plan', 'caregiver', 'discharge', 'en', 'plain', 'Start home antibiotics when sputum turns yellow or green; seek urgent care for increased breathlessness, confusion or drowsiness; keep short-acting bronchodilators available (KCR-0017/0018).', 'active'),
   ('7503e63e-ce51-52a2-afa7-c3b22ae82558', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-COPD-CLINICIAN'), 'EDU-COPD-CLINICIAN', 'COPD reasoning summary', 'clinician', 'explanation', 'en', 'plain', 'Render GOLD severity grade, evidence, treatment/escalation rationale and LTOT/rehabilitation plan.', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.education_condition (id, education_id, condition_id, weight) VALUES
   ('7a167063-4b6b-520e-9588-551b470943e7', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-SMOKING-CESSATION'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 1.0),
   ('5932073f-4d6a-5e25-a46f-53c0e1156d93', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-SMOKING-CESSATION'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 1.0),
   ('3a3c0d9a-f29c-5b1d-8ea5-d0e8e4861bf3', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-PULMONARY-REHAB'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 1.0),
   ('90d09ae9-d1ea-57a3-b094-18c66d0f4b2d', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-PULMONARY-REHAB'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 1.0),
   ('fbcc1bd5-a68f-5153-9129-4557004bfece', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-VACCINES'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 1.0),
   ('888009bc-b96e-5239-92e6-87bd87dbfc0d', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-VACCINES'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 1.0),
   ('bc3bf5e4-3845-5552-8f99-b0cb0689b24d', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-LTOT'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 1.0),
   ('28d66546-4f31-5f18-aef4-27ea1b71bff0', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-LTOT'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 1.0),
   ('4ff73d98-11b0-5221-a522-79b418a958ed', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-EXACERBATION-PLAN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 1.0),
   ('52b2e457-cb7b-5111-9d5b-8f02b5930ef1', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-EXACERBATION-PLAN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 1.0),
   ('69c02790-3189-5b23-8bce-f786f13c77ba', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-CLINICIAN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD'), 1.0),
   ('0b963fa5-a645-52b0-a52f-f612409dac6e', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-COPD-CLINICIAN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-COPD-EXACERBATION'), 1.0)
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 7. governance.knowledge_object - COPD pathway objects
-- ---------------------------------------------------------------------------
INSERT INTO governance.knowledge_object (id, object_code, knowledge_type, canonical_name, description, source_claim_code, jurisdiction_code, population_code, evidence_level_code, lifecycle_status, confidence, is_active, status) VALUES
   ('cb0f3e36-0770-5e2c-96aa-59327f6fa56d', 'PROT-COPD-EXACERBATION', 'PROTOCOL', 'Acute COPD exacerbation pathway', 'Population-aware adult acute COPD exacerbation pathway: ABC, controlled oxygen 88-92%, ABG, bronchodilators + corticosteroids + antibiotics, clearance, CXR, NIV escalation, critical care, discharge prevention.', 'KCR-0018', 'JUR-GLOBAL', 'POP-ADULT', 'EV-C', 'ACTIVE', 0.95, true, 'active'),
   ('8dbc3627-100d-559c-8603-42218ca4dd64', 'SCORE-GOLD', 'INTERPRETATION', 'GOLD airflow limitation severity', 'GOLD 1-4 severity by post-bronchodilator FEV1 % predicted with FEV1/FVC <0.70 (KCR-0016).', 'KCR-0016', 'JUR-GLOBAL', 'POP-ADULT', 'EV-C', 'ACTIVE', 0.95, true, 'active'),
   ('711d09e2-7a59-5f74-a1f7-94cf0253216a', 'MED-TIOTROPIUM', 'DRUG', 'Tiotropium (LAMA)', 'Long-acting muscarinic antagonist improving lung function, dyspnoea and quality of life in COPD (KCR-0017).', 'KCR-0017', 'JUR-GLOBAL', 'POP-ADULT', 'EV-C', 'ACTIVE', 0.95, true, 'active'),
   ('381a9e24-41c7-56a6-90e7-b2dc41a709d4', 'DOSE-COPD', 'DOSING_RULE', 'COPD dose rules', 'Population-aware dose rules for COPD maintenance and exacerbation drugs grounded to KCR-0017/0018.', 'KCR-0017', 'JUR-GLOBAL', 'POP-ADULT', 'EV-C', 'ACTIVE', 0.95, true, 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO governance.knowledge_object_version (object_id, version_no, version_code, change_note, lifecycle_status, source_claim_code, created_by)
SELECT ko.id, 1, 'GO-V-R6-' || ko.object_code, 'R6 COPD pathway release (KCR-0013..0018).', 'ACTIVE', ko.source_claim_code, 'Dr A Otieno'
FROM governance.knowledge_object ko WHERE ko.object_code IN ('PROT-COPD-EXACERBATION', 'SCORE-GOLD', 'MED-TIOTROPIUM', 'DOSE-COPD')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('65e6517c-569a-5529-9b53-268141aeeb97', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0018'), 'governance.knowledge_object', 'cb0f3e36-0770-5e2c-96aa-59327f6fa56d', 'PROT-COPD-EXACERBATION', 'derived_from')   ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('e59af25f-6ef5-5a0b-9c4f-4d5fffaa9434', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0016'), 'governance.knowledge_object', '8dbc3627-100d-559c-8603-42218ca4dd64', 'SCORE-GOLD', 'derived_from')   ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('6104dd9c-3dea-577d-845b-1b3519ad285b', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0017'), 'governance.knowledge_object', '711d09e2-7a59-5f74-a1f7-94cf0253216a', 'MED-TIOTROPIUM', 'derived_from')   ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('95260192-9ec2-5c1b-a623-5cebb4431ad7', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'KCR-0017'), 'governance.knowledge_object', '381a9e24-41c7-56a6-90e7-b2dc41a709d4', 'DOSE-COPD', 'derived_from')   ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 8. tracking.respiratory_master_matrix - COPD status
-- ---------------------------------------------------------------------------
UPDATE tracking.respiratory_master_matrix SET status='VERIFIED', source_ground='Kumar & Clark 10e p955-957 (KCR-0013..0016)',
       notes='COPD definition, chronic bronchitis, clinical features, investigations, GOLD severity classification; adult pathway active.',
       updated_at=now() WHERE item_code='COND-COPD';
UPDATE tracking.respiratory_master_matrix SET status='VERIFIED', source_ground='Kumar & Clark 10e p959-960 (KCR-0018)',
       notes='Acute exacerbation pathway: ABC, controlled oxygen 88-92%, ABG, bronchodilators + corticosteroids + antibiotics, clearance, CXR, NIV escalation, critical care.',
       updated_at=now() WHERE item_code='COND-COPD-EXACERBATION';
UPDATE tracking.respiratory_master_matrix SET status='GROUNDED', source_ground='Kumar & Clark 10e p957-960 (KCR-0017/0018)',
       notes='Maintenance (SABA/LABA/LAMA/PDE4/mucolytic/ICS/LTOT/rehab/vaccines) + exacerbation management + BODE prognosis covered.',
       updated_at=now() WHERE item_code='LONG-COPD';
