-- =============================================================================
-- AMEXAN Medical Knowledge Compiler — R1 respiratory source_claim seed
-- KUMAR_CLARK_10_2017 (KC-C28) + NELSON_ILLUSTRATED_2017 (BN-C01)
-- Claim codes KCR-xxxx / BNR-xxxx, grounded to printed pages, status VERIFIED
-- GENERATED FILE — do not edit by hand. Regenerate with:
--   python knowledge-compiler/build_r1_claims.py <out>
-- =============================================================================

INSERT INTO knowledge.source_claim (claim_id, claim_code, source_version_id, chapter_id, chunk_id, page_start, page_end, claim_type, claim_kind, claim_text, knowledge_type, contract, confidence, status) VALUES
   ('RC-000001', 'KCR-0001', 'KUMAR_CLARK_10_2017', 'KC-C28', 'd133e703-46c8-5a26-a05b-0bd6c507b385', 927, 927, 'CLINICAL_METHOD', 'history_section', 'The core respiratory symptoms in the medical history are cough, sputum production, breathlessness, chest pain, haemoptysis and wheeze; specify the acuity of onset, the change over time and any change in symptoms with location.', 'clinical_method', '{"what_is_it": "core respiratory symptom set (adult)", "what_connects_to": "cough graph, dyspnoea graph, haemoptysis red flags", "source_support": "Kumar & Clark 10e ch28 p927"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000002', 'KCR-0002', 'KUMAR_CLARK_10_2017', 'KC-C28', 'd133e703-46c8-5a26-a05b-0bd6c507b385', 927, 927, 'CLINICAL_METHOD', 'history_section', 'Systemic symptoms relevant to respiratory disease include weight loss, malaise and night sweats; occupational exposure, smoking history, recreational drug use, family history, childhood history and travel history are all relevant.', 'clinical_method', '{"what_is_it": "systemic + exposure domains for respiratory history", "what_fact_produces": "WEIGHT_LOSS, TB_CONTACT, SMOKING_STATUS, SMOKING_PACK_YEARS", "source_support": "Kumar & Clark 10e ch28 p927"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000003', 'KCR-0003', 'KUMAR_CLARK_10_2017', 'KC-C28', '45737756-dbe7-588c-ae16-ea806b31f983', 964, 964, 'RESPIRATORY_METHOD', 'definition', 'Community-acquired pneumonia (CAP) presents with a dry or productive cough, sometimes with haemoptysis, breathlessness and fever; chest pain is commonly pleuritic due to pleural inflammation and a pleural rub may be heard early.', 'medicine', '{"what_is_it": "CAP clinical presentation", "what_fact_produces": "COUGH_PRODUCTIVITY, COUGH_DURATION_DAYS, FEVER_PRESENT, CHEST_PAIN_PLEURITIC, DYSPNOEA_PRESENT", "source_support": "Kumar & Clark 10e ch28 p964"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000004', 'KCR-0004', 'KUMAR_CLARK_10_2017', 'KC-C28', '45737756-dbe7-588c-ae16-ea806b31f983', 964, 964, 'RESPIRATORY_METHOD', 'rule', 'A swinging fever in pneumonia may indicate empyema; in the elderly CAP can present with confusion or non-specific symptoms such as recurrent falls, so pneumonia should always be considered in sick elderly patients.', 'medicine', '{"what_is_it": "pneumonia atypical-presentation warning", "what_fact_produces": "CHILLS, CONFUSION, FEVER_PRESENT", "source_support": "Kumar & Clark 10e ch28 p964"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000005', 'KCR-0005', 'KUMAR_CLARK_10_2017', 'KC-C28', '45737756-dbe7-588c-ae16-ea806b31f983', 964, 964, 'RESPIRATORY_METHOD', 'threshold', 'CURB-65 severity scoring: 1 point each for confusion, urea >7 mmol/L, respiratory rate >30/min, systolic BP <90 or diastolic BP <60 mmHg, age >65. Score 0-1 treat as outpatient, score 2 admit to hospital, score 3+ often requires ITU care.', 'medicine', '{"what_is_it": "CURB-65 severity threshold (adult CAP)", "what_fact_produces": "RESP_RATE, CONFUSION, SYSTOLIC_BP, AGE", "source_support": "Kumar & Clark 10e ch28 p964"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000006', 'KCR-0006', 'KUMAR_CLARK_10_2017', 'KC-C28', '45737756-dbe7-588c-ae16-ea806b31f983', 964, 964, 'RESPIRATORY_METHOD', 'management', 'Mild CAP is treated at home with standard oral antibiotics (amoxicillin, or clarithromycin for penicillin allergy); chest X-ray is not routinely needed unless the patient fails to improve after 48-72 hours.', 'guideline_activity', '{"what_is_it": "mild CAP ambulatory management", "what_connects_to": "protocol action for mild CAP", "source_support": "Kumar & Clark 10e ch28 p964"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000007', 'KCR-0007', 'KUMAR_CLARK_10_2017', 'KC-C28', '78cbd381-63bf-580f-b6b9-5f3deb58759d', 965, 965, 'RESPIRATORY_METHOD', 'investigation', 'All patients admitted with suspected CAP need a chest X-ray, blood tests and microbiological tests; radiological abnormalities can lag behind clinical signs, so a normal CXR should be repeated after 2-3 days and 6 weeks later to rule out an underlying bronchial malignancy.', 'guideline_activity', '{"what_is_it": "admitted CAP investigation set", "what_fact_produces": "CXR_OPACITY, SPUTUM_CULTURE, BLOOD_CULTURE", "source_support": "Kumar & Clark 10e ch28 p965"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000008', 'KCR-0008', 'KUMAR_CLARK_10_2017', 'KC-C28', '78cbd381-63bf-580f-b6b9-5f3deb58759d', 965, 965, 'RESPIRATORY_METHOD', 'threshold', 'Arterial blood gas analysis is necessary if oxygen saturation is below 94%; supplemental oxygen should maintain saturations 94-98%, or 88-92% in patients with known COPD at risk of CO2 retention.', 'medicine', '{"what_is_it": "oxygen target threshold", "what_fact_produces": "SPO2, PAO2", "source_support": "Kumar & Clark 10e ch28 p965"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000009', 'KCR-0009', 'KUMAR_CLARK_10_2017', 'KC-C28', '78cbd381-63bf-580f-b6b9-5f3deb58759d', 965, 965, 'RESPIRATORY_METHOD', 'management', 'In severe CAP the first dose of antibiotic should be given within 1 hour of identifying high-risk criteria and must not be delayed while investigations are awaited; switch from parenteral to oral antibiotics once the temperature has settled for 24 hours.', 'guideline_activity', '{"what_is_it": "timely antibiotic escalation", "what_connects_to": "protocol step (adult CAP)", "source_support": "Kumar & Clark 10e ch28 p965"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000010', 'KCR-0010', 'KUMAR_CLARK_10_2017', 'KC-C28', '78cbd381-63bf-580f-b6b9-5f3deb58759d', 965, 965, 'RESPIRATORY_METHOD', 'rule', 'Parapneumonic effusion complicates around one-third to one-half of CAP; an exudative effusion with pleural fluid pH below 7.2 is strongly suggestive of empyema, which should be drained urgently.', 'medicine', '{"what_is_it": "effusion / empyema complication of CAP", "what_connects_to": "pleural effusion differential, empyema complication", "source_support": "Kumar & Clark 10e ch28 p965"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000011', 'KCR-0011', 'KUMAR_CLARK_10_2017', 'KC-C28', '45737756-dbe7-588c-ae16-ea806b31f983', 964, 964, 'RESPIRATORY_METHOD', 'risk_factor', 'Risk factors for community-acquired pneumonia include age under 16 or over 65 years, HIV infection, diabetes mellitus, chronic kidney disease, malnutrition, recent viral respiratory infection, smoking, excess alcohol and immunosuppressant therapy.', 'medicine', '{"what_is_it": "CAP risk factors", "what_fact_produces": "AGE, SMOKING_STATUS, HIV_STATUS, DIABETES_STATUS, CKD_STATUS", "source_support": "Kumar & Clark 10e ch28 p964"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000012', 'KCR-0012', 'KUMAR_CLARK_10_2017', 'KC-C28', '45737756-dbe7-588c-ae16-ea806b31f983', 964, 964, 'RESPIRATORY_METHOD', 'definition', 'Infection in the lung can be localized to one or more lobes (lobar pneumonia) or diffuse with lobular involvement centred on bronchi and bronchioles (bronchopneumonia); in 30-50% of CAP cases no organism is identifiable.', 'medicine', '{"what_is_it": "CAP anatomical classification", "what_connects_to": "CXR lobar vs bronchopneumonia interpretation", "source_support": "Kumar & Clark 10e ch28 p964"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000013', 'BNR-0001', 'NELSON_ILLUSTRATED_2017', 'BN-C01', '3f8f5a2d-d13f-5145-bf5a-6c404ce588d2', 166, 166, 'PAEDIATRIC_RESPIRATORY', 'definition', 'In children pneumonia is an infection of the lower respiratory tract involving airways and parenchyma with consolidation of the alveolar spaces; pneumonitis is lung inflammation that may or may not be associated with consolidation.', 'medicine', '{"what_is_it": "paediatric pneumonia definition", "what_connects_to": "pneumonia differential (paediatric overlay)", "source_support": "Illustrated Baby Nelson Pulmonology p166"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000014', 'BNR-0002', 'NELSON_ILLUSTRATED_2017', 'BN-C01', '3f8f5a2d-d13f-5145-bf5a-6c404ce588d2', 166, 166, 'PAEDIATRIC_RESPIRATORY', 'question', 'Symptoms of pneumonia in children: cough that is dry then becomes productive, dyspnoea with grunting, fever, malaise and toxaemia; abdominal pain may occur referred from lower-lobe pneumonia.', 'medicine', '{"what_is_it": "paediatric pneumonia symptom set", "what_fact_produces": "COUGH_PRESENT, COUGH_PRODUCTIVITY, FEVER_PRESENT, DYSPNOEA_PRESENT, ABDO_PAIN_PRESENT", "source_support": "Illustrated Baby Nelson Pulmonology p166"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000015', 'BNR-0003', 'NELSON_ILLUSTRATED_2017', 'BN-C01', '3f8f5a2d-d13f-5145-bf5a-6c404ce588d2', 166, 166, 'PAEDIATRIC_RESPIRATORY', 'examination', 'Tachypnoea is the most consistent clinical manifestation of pneumonia in children; respiratory distress is signalled by nasal flaring, chest-wall retractions (chest indrawing) and grunting.', 'medicine', '{"what_is_it": "paediatric pneumonia cardinal signs", "what_fact_produces": "RESP_RATE, FAST_BREATHING, NASAL_FLARING, CHEST_INDRAWING, GRUNTING", "source_support": "Illustrated Baby Nelson Pulmonology p166"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000016', 'BNR-0004', 'NELSON_ILLUSTRATED_2017', 'BN-C01', '3f8f5a2d-d13f-5145-bf5a-6c404ce588d2', 166, 166, 'PAEDIATRIC_RESPIRATORY', 'red_flag', 'Cyanosis and lethargy in pneumonia indicate severe infection, especially in infants, and warrant urgent escalation.', 'medicine', '{"what_is_it": "paediatric pneumonia danger signal", "what_fact_produces": "CYANOSIS, LETHARGY", "source_support": "Illustrated Baby Nelson Pulmonology p166"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000017', 'BNR-0005', 'NELSON_ILLUSTRATED_2017', 'BN-C01', '0cd980d1-c71d-5d28-b95f-dcad77afc0e4', 167, 167, 'PAEDIATRIC_RESPIRATORY', 'rule', 'In children a large pleural effusion, lobar consolidation and a high fever at onset suggest a bacterial aetiology; interstitial pneumonia shows minimal chest findings with prolonged expiration and wheezes common.', 'medicine', '{"what_is_it": "bacterial vs viral pneumonia distinction (child)", "what_fact_produces": "CXR_OPACITY, FEVER_PRESENT, WHEEZE_PRESENT", "source_support": "Illustrated Baby Nelson Pulmonology p167"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000018', 'BNR-0006', 'NELSON_ILLUSTRATED_2017', 'BN-C01', 'c8d48b5f-e21c-5f8c-9e0f-cd4d4f0defb6', 171, 171, 'PAEDIATRIC_RESPIRATORY', 'management', 'Supportive care of childhood pneumonia: bed rest, humidified oxygen inhalation with restricted IV fluids, symptomatic treatment (antipyretics for fever) and treatment of complications such as heart failure; oral zinc 10-20 mg/day is recommended as an add-on in developing countries.', 'guideline_activity', '{"what_is_it": "paediatric pneumonia supportive care", "what_connects_to": "protocol action (paediatric pneumonia)", "source_support": "Illustrated Baby Nelson Pulmonology p171"}'::jsonb, 0.9, 'VERIFIED'),
   ('RC-000019', 'BNR-0007', 'NELSON_ILLUSTRATED_2017', 'BN-C01', 'c8d48b5f-e21c-5f8c-9e0f-cd4d4f0defb6', 171, 171, 'PAEDIATRIC_RESPIRATORY', 'management', 'Empirical antibiotics for childhood pneumonia are chosen by clinical picture, chest X-ray and age: milder cases amoxicillin 50-90 mg/kg/dose; hospitalized infants under 4 weeks IV ampicillin plus an aminoglycoside; infants 4-12 weeks IV ampicillin for 7-10 days; older children ampicillin or penicillin G if fully immunized, otherwise parenteral cefotaxime or ceftriaxone; add vancomycin or clindamycin for suspected staphylococcal infection; macrolides for Mycoplasma. Duration is 10-14 days, or 5 days if azithromycin.', 'guideline_activity', '{"what_is_it": "paediatric pneumonia empirical antibiotic protocol", "what_connects_to": "protocol step (paediatric pneumonia)", "source_support": "Illustrated Baby Nelson Pulmonology p171"}'::jsonb, 0.9, 'VERIFIED')
  ON CONFLICT DO NOTHING;
