-- =============================================================================
-- AMEXAN Medical Knowledge Compiler - R7 heart failure decompensation (adult)
-- Congestive heart failure / decompensation grounded to Hutchison 24e p193-198
-- (claims HCH13-0001..0006), p123-129 (HCH9-0001..0003) and
-- Kumar & Clark 10e p929/937 (KCR-0019..0020). Adds NYHA score, investigations,
-- full adult decompensation pathway, advice-level diuretic + ACE (no dose rows).
-- GENERATED FILE - do not edit by hand. Regenerate with:
--   python knowledge-compiler/build_r7_heart_failure.py <out>
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. knowledge.source_claim - heart failure claims
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.source_claim (claim_id, claim_code, source_version_id, chapter_id, chunk_id, page_start, page_end, claim_type, claim_kind, claim_text, knowledge_type, contract, confidence, status) VALUES
   ('f706718d-7eda-5879-8965-ae6c0916f630', 'HCH13-0001', 'HUTCHISON_24_2018', 'H1-C13', '019e65f6-2e79-5987-a4cf-f0a1b6b52068', '193', '193', 'CARDIOVASCULAR_METHOD', 'definition', 'Congestive heart failure - typical patient: middle-aged (male) or elderly (either sex) patient with a history of myocardial infarction or long-standing hypertension; in cases where there is no clear cause, always enquire about alcohol consumption. Major symptoms: exertional fatigue and shortness of breath, with orthopnoea and paroxysmal nocturnal dyspnoea in advanced cases. Major signs: fluid retention - basal crackles, raised JVP, peripheral oedema; reduced cardiac output - cool skin, peripheral cyanosis; other findings - third heart sound.', 'medicine', '{"what_is_it":"Congestive heart failure clinical features (Box 13.10)","what_fact_produces":"DYSPNOEA_PRESENT, ORTHOPNOEA, PND, PERIPHERAL_OEDEMA, CRACKLES, JUGULAR_VENOUS_DISTENTION","source_support":"Hutchison 24e p193"}'::jsonb, 0.9, 'VERIFIED'),
   ('58ec967e-975f-55f0-80b5-6893845b7bd6', 'HCH13-0002', 'HUTCHISON_24_2018', 'H1-C13', '019e65f6-2e79-5987-a4cf-f0a1b6b52068', '193', '193', 'CARDIOVASCULAR_METHOD', 'investigation', 'Congestive heart failure diagnosis - ECG: usually abnormal, often showing Q waves (previous myocardial infarction), left ventricular hypertrophy (hypertension) or left bundle branch block (LBBB); chest X-ray: cardiac enlargement with congested lung fields; echocardiogram: left ventricular dilatation with regional (coronary heart disease) or global (cardiomyopathy) contractile impairment; raised B-type natriuretic peptide (BNP) useful in cases of diagnostic uncertainty; renal function as prelude to diuretic and angiotensin converting enzyme (ACE) inhibitor therapy; blood count to rule out anaemia. The echocardiogram is the single most important diagnostic test in the patient with heart failure.', 'medicine', '{"what_is_it":"Congestive heart failure diagnosis + investigations (Box 13.10)","what_connects_to":"INV-ECG, INV-CXR, INV-ECHO, INV-BNP, INV-UREA-CREAT, INV-FBC","source_support":"Hutchison 24e p193"}'::jsonb, 0.9, 'VERIFIED'),
   ('d55e88ee-a07a-5793-8265-273d250cb037', 'HCH13-0003', 'HUTCHISON_24_2018', 'H1-C13', '019e65f6-2e79-5987-a4cf-f0a1b6b52068', '193', '193', 'CARDIOVASCULAR_METHOD', 'threshold', 'New York Heart Association (NYHA) classification of breathlessness in heart failure (Table 13.2): Class I - asymptomatic; Class II - symptoms on normal exertion, e.g. walking up a flight of stairs; Class III - symptoms on minimal exertion, e.g. getting dressed; Class IV - symptoms at rest.', 'medicine', '{"what_is_it":"NYHA functional classification","what_fact_produces":"DYSPNOEA_AT_REST, DYSPNOEA_ON_MINIMAL_EXERTION, DYSPNOEA_ON_NORMAL_EXERTION","source_support":"Hutchison 24e p193 (Table 13.2)"}'::jsonb, 0.9, 'VERIFIED'),
   ('96f1e283-5f23-5145-959a-50e38fbb989d', 'HCH13-0004', 'HUTCHISON_24_2018', 'H1-C13', '019e65f6-2e79-5987-a4cf-f0a1b6b52068', '193', '193', 'CARDIOVASCULAR_METHOD', 'red_flag', 'Acute left ventricular failure - typical patient: acute myocardial infarction or known left ventricular disease. Major symptoms: severe dyspnoea, orthopnoea, frothy sputum. Major signs: low-output state (hypotension, oliguria, cold periphery), tachycardia, S3, sweating, crackles at lung bases. Diagnosis: chest X-ray shows bilateral air space consolidation with typical perihilar distribution; echocardiogram usually confirms left ventricular disease; ECG may show evidence of acute or previous myocardial infarction; blood gas analysis shows variable hypoxaemia. Vital to exclude valvular disease which is potentially correctable by surgery.', 'medicine', '{"what_is_it":"Acute left ventricular failure presentation (Box 13.9)","what_fact_produces":"DYSPNOEA_PRESENT, ORTHOPNOEA, CRACKLES","what_connects_to":"INV-ECG, INV-CXR, INV-ECHO","source_support":"Hutchison 24e p193 (Box 13.9)"}'::jsonb, 0.9, 'VERIFIED'),
   ('e0edbe97-600c-52ba-b922-7fde54fad8f9', 'HCH13-0005', 'HUTCHISON_24_2018', 'H1-C13', '7ac14d53-c395-5ca0-97d4-826c5d692565', '196', '196', 'CARDIOVASCULAR_METHOD', 'examination', 'Subcutaneous oedema that pits on digital pressure is a cardinal feature of congestive heart failure; pressure should be applied over a bony prominence (tibia, lateral malleoli, sacrum). Oedema is caused by salt and water retention by the kidney: reduced sodium delivery to the nephron (from constriction of preglomerular arterioles in response to sympathetic activation and angiotensin II) and increased sodium reabsorption (proximal tubule early in failure; later renin-angiotensin activation stimulates aldosterone, increasing distal sodium reabsorption). Salt and water retention expands plasma volume and capillary hydrostatic pressure so fluid accumulates in the interstitial space; oedema is most prominent around the ankles in the ambulant patient and over the sacrum in the bedridden patient, and may involve legs, genitalia and trunk in advanced failure, with ascites and pleural/pericardial transudation.', 'medicine', '{"what_is_it":"Pitting oedema - cardinal feature of congestive heart failure + mechanisms","what_fact_produces":"PERIPHERAL_OEDEMA","source_support":"Hutchison 24e p196"}'::jsonb, 0.9, 'VERIFIED'),
   ('a98a7729-9a05-55b1-af46-1c676edd1ead', 'HCH13-0006', 'HUTCHISON_24_2018', 'H1-C13', '959fd9ed-86c8-56df-9fa0-ba6e67cf6964', '198', '198', 'CARDIOVASCULAR_METHOD', 'examination', 'The jugular venous pressure (JVP) is assessed from the waveform of the internal jugular vein adjacent to the medial border of the sternocleidomastoid muscle; distension of the external jugular vein is a useful clue to an elevated JVP. It is measured in centimetres vertically from the sternal angle to the top of the venous waveform; the normal upper limit is 4 cm (about 9 cm above the right atrium, corresponding to 6 mmHg). Elevation of the JVP indicates a raised right atrial pressure unless the superior vena cava is obstructed. Causes of elevated JVP (Box 13.12) include congestive heart failure, cor pulmonale, pulmonary embolism, right ventricular infarction, tricuspid valve disease, tamponade, constrictive pericarditis, hypertrophic/restrictive cardiomyopathy, superior vena cava obstruction and iatrogenic fluid overload.', 'medicine', '{"what_is_it":"Jugular venous pressure assessment + causes of elevated JVP (Box 13.12)","what_fact_produces":"JUGULAR_VENOUS_DISTENTION","source_support":"Hutchison 24e p198 (Box 13.12)"}'::jsonb, 0.9, 'VERIFIED'),
   ('6f419b30-af78-57a2-a887-26b68872bf3a', 'HCH9-0001', 'HUTCHISON_24_2018', 'H1-C09', '22bc3a24-79d6-526b-91bb-3dbee146ba26', '123', '123', 'EMERGENCY_METHOD', 'red_flag', 'In the emergency patient, a raised jugular venous pressure may suggest early heart failure; precordial auscultation may reveal a pericardial rub. Important examination features in the initial rapid assessment include the fine crepitations of pulmonary oedema, the hyperresonant percussion and tracheal deviation of pneumothorax, and asymmetric blood pressure readings consistent with thoracic aortic dissection.', 'medicine', '{"what_is_it":"Raised JVP may suggest early heart failure; fine crepitations of pulmonary oedema","what_fact_produces":"JUGULAR_VENOUS_DISTENTION, CRACKLES","source_support":"Hutchison 24e p123"}'::jsonb, 0.9, 'VERIFIED'),
   ('cd3a0152-7bff-526b-a795-5b454d53d3ca', 'HCH9-0002', 'HUTCHISON_24_2018', 'H1-C09', '3126b5c6-8d52-5a42-9cb9-2a48293eabba', '124', '124', 'EMERGENCY_METHOD', 'management', 'The breathless patient should be placed in a safe, monitored (ECG and pulse oximetry) environment; act quickly if there is visible distress, use of accessory muscles, high respiratory rate, high pulse rate, cyanosis or low oxygen saturations. The immediate response is to administer high-flow oxygen unless there is good evidence that this has, on this or previous occasions, caused breathing difficulties (most commonly chronic obstructive pulmonary disease). In most cases arrangements for urgent ECG and chest X-ray (CXR) will be made immediately, before the initial clinical assessment is complete. Pulmonary oedema is among the potentially life-threatening conditions presenting as breathlessness (Table 9.4). In chest pain, troponin is measured in blood (released when cardiac myocytes undergo ischaemic necrosis); a negative result indicates the risk of a serious acute cardiac event in the ensuing 30 days is extremely low.', 'medicine', '{"what_is_it":"Breathless patient: monitored environment, high-flow O2 unless COPD, urgent ECG + CXR","what_connects_to":"INV-ECG, INV-CXR, INV-TROPONIN, MON-SPO2","source_support":"Hutchison 24e p124 (Table 9.4)"}'::jsonb, 0.9, 'VERIFIED'),
   ('d6420ee4-e7d9-536d-a3cd-c01fd817f4f9', 'HCH9-0003', 'HUTCHISON_24_2018', 'H1-C09', 'bc7582d0-879d-53aa-b4e7-7c4e935252bb', '129', '129', 'EMERGENCY_METHOD', 'red_flag', 'Cardiogenic shock is a failure of the heart to pump blood effectively to meet peripheral oxygen demands, most frequently due to a large myocardial infarction but also to cardiac dysrhythmias, other causes of cardiac muscle pump failure (myocarditis, cardiomyopathy) or acute cardiac valve problems. There is usually a narrow pulse pressure; it may be associated with preceding chest pain, palpitations or breathlessness (in particular orthopnoea), and there are frequently auscultatory features of pulmonary oedema. An ECG is often informative and may show changes of recent infarction, dysrhythmia or nonspecific changes of pericarditis, myocarditis and cardiomyopathy. Treatment largely depends on the cause; inotropic support and invasive measures are frequently required.', 'medicine', '{"what_is_it":"Cardiogenic shock - presentation and escalation","what_connects_to":"REF-CRITICAL-CARE, INV-ECG","source_support":"Hutchison 24e p129"}'::jsonb, 0.9, 'VERIFIED'),
   ('8a6b240b-3ec8-5bd5-950e-15fad4c9a6b4', 'KCR-0019', 'KUMAR_CLARK_10_2017', 'KC-C28', '8015cb33-f797-5c8a-aeaf-c4e37beafd95', '929', '929', 'RESPIRATORY_METHOD', 'investigation', 'On the chest X-ray, heart size should be less than 50% of the thoracic width on a PA chest film; assess the heart borders. Cardiomegaly may be caused by hypertension, valvular disease, heart failure or cardiomyopathy. Interstitial changes may be caused by pulmonary oedema or fibrosis; loss of the costophrenic angle is usually due to pleural effusions.', 'medicine', '{"what_is_it":"CXR interpretation: heart size <50% thoracic width; cardiomegaly causes","what_connects_to":"INV-CXR","source_support":"Kumar & Clark 10e p929"}'::jsonb, 0.9, 'VERIFIED'),
   ('55213128-67ac-5489-99db-9c96ecafcf74', 'KCR-0020', 'KUMAR_CLARK_10_2017', 'KC-C28', '68e27abe-86b4-5d63-926e-03a6126046ba', '937', '937', 'RESPIRATORY_METHOD', 'definition', 'Orthopnoea is breathlessness on lying down; while classically linked to heart failure it is partly due to the weight of the abdominal contents pushing the diaphragm up into the thorax. Paroxysmal nocturnal dyspnoea (PND) describes acute episodes of breathlessness at night, typically due to heart failure. Breathlessness can be graded using the Medical Research Council (MRC) grading of dyspnoea (Box 28.5).', 'medicine', '{"what_is_it":"Orthopnoea and paroxysmal nocturnal dyspnoea - typically due to heart failure","what_fact_produces":"ORTHOPNOEA, PND","source_support":"Kumar & Clark 10e p937"}'::jsonb, 0.9, 'VERIFIED')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 1. knowledge.condition - COND-HF-DECOMPENSATION (HEART-FAILURE exists)
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.condition (id, concept_id, condition_code, canonical_name, description, condition_type, status) VALUES
   ('77d87c89-f3b3-5f04-864c-19f5f7efa6e1', NULL, 'COND-HF-DECOMPENSATION', 'Heart failure decompensation', 'Acute worsening of heart failure with congestion (dyspnoea, orthopnoea, paroxysmal nocturnal dyspnoea, peripheral oedema, raised JVP, basal crackles) and/or low cardiac output (fatigue, cool periphery, hypotension), most often on a background of ischaemic or hypertensive left ventricular disease; severe cases present as acute left ventricular failure or cardiogenic shock.', 'acute', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.phenotype_differential (id, phenotype_id, condition_id, relationship_type, weight) VALUES
   ('73f0ef33-ee76-53d7-8cb5-f4d4d2dda4bc', (SELECT id FROM knowledge.phenotype WHERE phenotype_code = 'PHEN-CHF-CONGESTIVE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), 'associated', '0.95'),
   ('5a4620e1-38dd-5cf2-90e3-ebd64b44cc8e', (SELECT id FROM knowledge.phenotype WHERE phenotype_code = 'PHEN-CHF-CONGESTIVE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), 'associated', '0.90'),
   ('7206beea-a7b3-5043-a134-6b5ce3534412', (SELECT id FROM knowledge.phenotype WHERE phenotype_code = 'PHEN-ACUTE-HYPOXAEMIC'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), 'associated', '0.40'),
   ('d1b1fdad-b2b7-5a09-95fd-74065c8ca8f2', (SELECT id FROM knowledge.phenotype WHERE phenotype_code = 'PHEN-RESPIRATORY-FAILURE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), 'associated', '0.50')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. clinical.fact_definition - NYHA boolean facts
-- ---------------------------------------------------------------------------
INSERT INTO clinical.fact_definition (code, name, description, data_type, allow_multiple, is_active) VALUES
   ('DYSPNOEA_AT_REST', 'DYSPNOEA_AT_REST', 'Dyspnoea at rest - NYHA class IV (symptoms at rest)', 'boolean', false, true),
   ('DYSPNOEA_ON_MINIMAL_EXERTION', 'DYSPNOEA_ON_MINIMAL_EXERTION', 'Dyspnoea on minimal exertion (e.g. getting dressed) - NYHA class III', 'boolean', false, true),
   ('DYSPNOEA_ON_NORMAL_EXERTION', 'DYSPNOEA_ON_NORMAL_EXERTION', 'Dyspnoea on normal exertion (e.g. walking up a flight of stairs) - NYHA class II', 'boolean', false, true)
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2b. knowledge.severity_score - SCORE-NYHA (I-IV)
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.severity_score (id, score_code, canonical_name, description, condition_id, population, max_score, source_reference, status) VALUES
   ('bd83fb38-395b-5f58-a06a-c49a64a47e28', 'SCORE-NYHA', 'NYHA functional classification', 'NYHA I-IV functional class from exertional dyspnoea threshold (normal exertion / minimal exertion / at rest) per Hutchison 24e Table 13.2 (HCH13-0003).', (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), 'adult', 4, 'Hutchison 24e p193 (Table 13.2) - HCH13-0003', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.severity_score_component (id, score_id, component_code, component_name, condition, points, rationale, sort_order) VALUES
   ('f330b9bb-428c-5681-9f0e-aeb5ee33bc3d', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-NYHA'), 'NYHA-1', 'NYHA I - Asymptomatic', '{"type":"and","conditions":[{"type":"not","condition":{"type":"boolean","fact_code":"DYSPNOEA_AT_REST","expect":true}},{"type":"not","condition":{"type":"boolean","fact_code":"DYSPNOEA_ON_MINIMAL_EXERTION","expect":true}},{"type":"not","condition":{"type":"boolean","fact_code":"DYSPNOEA_ON_NORMAL_EXERTION","expect":true}}]}'::jsonb, '1', 'No dyspnoea on ordinary exertion; asymptomatic (HCH13-0003).', '10'),
   ('13136253-91cb-5a7f-9f8b-c5e509963f76', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-NYHA'), 'NYHA-2', 'NYHA II - Symptoms on normal exertion', '{"type":"and","conditions":[{"type":"boolean","fact_code":"DYSPNOEA_ON_NORMAL_EXERTION","expect":true},{"type":"not","condition":{"type":"boolean","fact_code":"DYSPNOEA_ON_MINIMAL_EXERTION","expect":true}},{"type":"not","condition":{"type":"boolean","fact_code":"DYSPNOEA_AT_REST","expect":true}}]}'::jsonb, '2', 'Symptoms on normal exertion, e.g. walking up a flight of stairs (HCH13-0003).', '11'),
   ('4336fa37-69bc-54b7-b829-e7499835b059', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-NYHA'), 'NYHA-3', 'NYHA III - Symptoms on minimal exertion', '{"type":"and","conditions":[{"type":"boolean","fact_code":"DYSPNOEA_ON_MINIMAL_EXERTION","expect":true},{"type":"not","condition":{"type":"boolean","fact_code":"DYSPNOEA_AT_REST","expect":true}}]}'::jsonb, '3', 'Symptoms on minimal exertion, e.g. getting dressed (HCH13-0003).', '12'),
   ('500be39d-1be7-544c-ba49-16d9d2c56d10', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-NYHA'), 'NYHA-4', 'NYHA IV - Symptoms at rest', '{"type":"boolean","fact_code":"DYSPNOEA_AT_REST","expect":true}'::jsonb, '4', 'Symptoms at rest (HCH13-0003).', '13')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.severity_score_interpretation (id, score_id, min_score, max_score, severity_label, disposition, recommendation) VALUES
   ('e67158ca-36fa-5eb8-8d44-8773caa73037', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-NYHA'), '1', '1', 'NYHA I - Asymptomatic', 'Outpatient', 'No symptoms on ordinary exertion; confirm cause (ischaemic/hypertensive/valvular), ECG, CXR, echo, BNP.'),
   ('2c4a1bb0-7c2e-5fe6-bcb2-f0da6b23325e', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-NYHA'), '2', '2', 'NYHA II - Mild', 'Outpatient', 'Symptoms on normal exertion (stairs); institute disease-modifying therapy, monitor fluid status and weight.'),
   ('adbb2ebb-8882-5e91-aaa5-94127e4adb00', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-NYHA'), '3', '3', 'NYHA III - Moderate', 'Refer', 'Symptoms on minimal exertion (dressing); refer for specialist review; optimise diuretic/ACE therapy.'),
   ('bba3f13c-f9a7-554f-bd10-11019f8c8977', (SELECT id FROM knowledge.severity_score WHERE score_code = 'SCORE-NYHA'), '4', '4', 'NYHA IV - Severe', 'Refer', 'Symptoms at rest; urgent referral/admission; acute decompensation pathway with oxygen, ECG, CXR, echo, BNP.')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2c. knowledge.fact_mapping - PERIPHERAL_OEDEMA + NYHA boolean reconciliation
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.fact_mapping (id, answer_option_id, fact_definition_code, value, is_active) VALUES
   ('ed18dbcc-6439-5b6e-a3d8-ad3e19f879db', (SELECT ao.id FROM knowledge.answer_option ao JOIN knowledge.question q ON q.id = ao.question_id WHERE q.question_code = 'LEG_SWELLING_ASK' AND ao.answer_code = 'YES'), 'PERIPHERAL_OEDEMA', 'true', true),
   ('e797700d-f5ed-5e5c-8d12-26704f97d96c', (SELECT ao.id FROM knowledge.answer_option ao JOIN knowledge.question q ON q.id = ao.question_id WHERE q.question_code = 'LEG_SWELLING_ASK' AND ao.answer_code = 'NO'), 'PERIPHERAL_OEDEMA', 'false', true),
   ('150462ed-34e3-51a5-b9f0-2124fefbad01', (SELECT ao.id FROM knowledge.answer_option ao JOIN knowledge.question q ON q.id = ao.question_id WHERE q.question_code = 'DYSPNOEA_SEVERITY' AND ao.answer_code = 'ON_EXERTION'), 'DYSPNOEA_ON_NORMAL_EXERTION', 'true', true),
   ('cc01dfd4-c3bf-59db-8b58-6c2923417db3', (SELECT ao.id FROM knowledge.answer_option ao JOIN knowledge.question q ON q.id = ao.question_id WHERE q.question_code = 'DYSPNOEA_SEVERITY' AND ao.answer_code = 'ON_WALKING'), 'DYSPNOEA_ON_MINIMAL_EXERTION', 'true', true),
   ('15f3193b-398d-50a6-ab09-d1252a134fc9', (SELECT ao.id FROM knowledge.answer_option ao JOIN knowledge.question q ON q.id = ao.question_id WHERE q.question_code = 'DYSPNOEA_SEVERITY' AND ao.answer_code = 'AT_REST'), 'DYSPNOEA_AT_REST', 'true', true)
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. knowledge.investigation - ECG / echo / BNP / troponin
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.investigation (id, concept_id, investigation_code, canonical_name, description, investigation_type, body_system_code, specimen, turn_around_minutes, preparation, status) VALUES
   ('98ec1390-5382-5045-89b6-b521886920fd', NULL, 'INV-ECG', '12-lead ECG', '12-lead electrocardiogram - in heart failure usually abnormal: Q waves (previous MI), left ventricular hypertrophy, left bundle branch block or dysrhythmia; in cardiogenic shock may show recent infarction or dysrhythmia.', 'physiological', 'CARDIOVASCULAR', NULL, NULL, NULL, 'active'),
   ('5b4f78cc-3189-5e07-b0af-90b9f2217115', NULL, 'INV-ECHO', 'Echocardiogram', 'Echocardiography - the single most important diagnostic test in heart failure: shows left ventricular dilatation with regional (coronary heart disease) or global (cardiomyopathy) contractile impairment; excludes correctable valvular disease.', 'imaging', 'CARDIOVASCULAR', NULL, NULL, NULL, 'active'),
   ('b1cbe02b-1d42-553c-a101-bce75eed8c59', NULL, 'INV-BNP', 'B-type natriuretic peptide', 'B-type natriuretic peptide (BNP) - raised BNP is useful in cases of diagnostic uncertainty in heart failure.', 'laboratory', 'CARDIOVASCULAR', NULL, NULL, NULL, 'active'),
   ('ef4209c3-42fc-543a-b698-a3ff36b5603a', NULL, 'INV-TROPONIN', 'Cardiac troponin', 'Cardiac troponin - released when cardiac myocytes undergo ischaemic necrosis; measured in emergency chest pain/breathlessness; a negative result indicates the risk of a serious acute cardiac event in the ensuing 30 days is extremely low.', 'laboratory', 'CARDIOVASCULAR', NULL, NULL, NULL, 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.investigation_condition (id, investigation_id, condition_id, weight, rationale) VALUES
   ('acf000a6-7f25-5bee-a637-6dfce6b5fb8a', (SELECT id FROM knowledge.investigation WHERE investigation_code = 'INV-ECG'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), '0.95', 'ECG usually abnormal in heart failure (HCH13-0002).'),
   ('49ea89e0-520d-5b33-bbc5-7f6298ba0acd', (SELECT id FROM knowledge.investigation WHERE investigation_code = 'INV-ECHO'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), '0.95', 'Echo is the single most important diagnostic test in heart failure (HCH13-0002).'),
   ('4d92a314-d41b-56bd-ba0d-94bc79cefabc', (SELECT id FROM knowledge.investigation WHERE investigation_code = 'INV-BNP'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), '0.85', 'Raised BNP useful in diagnostic uncertainty (HCH13-0002).'),
   ('43848ef4-73cd-5dcc-8f5b-3a09dfcb96f2', (SELECT id FROM knowledge.investigation WHERE investigation_code = 'INV-FBC'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), '0.50', 'Blood count to rule out anaemia (HCH13-0002).'),
   ('3177e515-4f58-5e58-be1f-9082671d3c4e', (SELECT id FROM knowledge.investigation WHERE investigation_code = 'INV-ECG'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), '0.95', 'ECG in acute decompensation may show MI, LBBB or dysrhythmia (HCH13-0002/0004).'),
   ('4189b02c-6466-51b1-893b-3949b7216dfa', (SELECT id FROM knowledge.investigation WHERE investigation_code = 'INV-CXR'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), '0.95', 'CXR: cardiac enlargement, congested lung fields, bilateral perihilar air-space consolidation (HCH13-0002/0004, KCR-0019).'),
   ('b400db5d-2999-5d8b-8bd1-e0ea7d4e9677', (SELECT id FROM knowledge.investigation WHERE investigation_code = 'INV-ECHO'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), '0.95', 'Echo confirms LV dilatation and contractile impairment; excludes correctable valvular disease (HCH13-0002/0004).'),
   ('4dc67709-9df3-5095-9a37-0d8d930d44e0', (SELECT id FROM knowledge.investigation WHERE investigation_code = 'INV-BNP'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), '0.85', 'Raised BNP useful in diagnostic uncertainty (HCH13-0002).'),
   ('974a25e5-9b62-52b0-8ac3-c153b01310cb', (SELECT id FROM knowledge.investigation WHERE investigation_code = 'INV-TROPONIN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), '0.60', 'Troponin measured in emergency chest pain/breathlessness; negative result lowers 30-day acute cardiac risk (HCH9-0002).')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. knowledge.monitoring - MON-WEIGHT (new)
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.monitoring (id, concept_id, monitoring_code, canonical_name, description, target_type, unit, body_system_code, normal_low, normal_high, status) VALUES
   ('ec7a4414-f44f-5fa2-b52e-b0c6b97e09e2', NULL, 'MON-WEIGHT', 'Daily body weight', 'Daily weight to track fluid retention and decongestion in heart failure; rapid gain reflects fluid overload (HCH13-0005).', 'numeric', 'kg', 'CONSTITUTIONAL', NULL, NULL, 'active')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 5. PROT-HF-DECOMP - full 12-step pathway (adult) - replaces the draft
-- ---------------------------------------------------------------------------
UPDATE knowledge.protocol SET status='active', canonical_name='Acute heart failure decompensation pathway',
       description='Adult acute heart failure decompensation: confirm decompensation, ABC + severity, upright + high-flow oxygen unless COPD, ECG, CXR, BNP + renal + FBC, echo, advice-level diuretic + ACE inhibitor, monitoring, cardiogenic shock escalation, education, NYHA grading.',
       population='adult', source_reference='Hutchison 24e p193-198 + Kumar & Clark 10e p929/937 (HCH13-0001..0006, HCH9-0001..0003, KCR-0019..0020)'
WHERE protocol_code='PROT-HF-DECOMP';
DELETE FROM knowledge.protocol_action WHERE protocol_id = (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP');
DELETE FROM knowledge.protocol_monitoring WHERE protocol_id = (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP');
DELETE FROM knowledge.protocol_step WHERE protocol_id = (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP');
DELETE FROM knowledge.protocol_condition WHERE protocol_id = (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP');

INSERT INTO knowledge.protocol_condition (id, protocol_id, condition_id, is_primary) VALUES
   ('a9acb639-297f-5fdc-9f9d-9cef460bee12', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), true),
   ('172e0c47-a3a3-5296-92b9-b6322e0031ea', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), false)
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_step (id, protocol_id, step_code, step_label, step_type, sequence_no, instruction, rationale, required) VALUES
   ('618e5360-a594-5e43-9f95-db338b4aad93', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-01', 'Confirm heart failure decompensation', 'eligibility', '10', 'Confirm acute decompensation of heart failure: worsening dyspnoea, orthopnoea, paroxysmal nocturnal dyspnoea, leg swelling/oedema, fatigue, on a background of ischaemic or hypertensive left ventricular disease (or known heart failure).', 'Congestion with or without low cardiac output characterises decompensation (HCH13-0001/0004/0005).', TRUE),
   ('549063c0-afd2-5188-8dde-635062955c18', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-02', 'Assess airway, breathing, circulation + severity', 'red_flag', '20', 'Rapid ABC assessment in a safe, monitored (ECG + pulse oximetry) environment; detect severe dyspnoea, orthopnoea, frothy sputum, low-output state (hypotension, oliguria, cold periphery), tachycardia, S3, sweating, crackles, cyanosis or narrow pulse pressure (cardiogenic shock).', 'Acute LVF and cardiogenic shock are emergencies (HCH13-0004, HCH9-0003).', TRUE),
   ('419e97fe-db8f-5995-8de6-bebacc1791e7', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-03', 'Position the patient upright and give oxygen', 'treatment', '30', 'Sit the patient upright. Administer high-flow oxygen unless there is good evidence it causes breathing difficulty (most commonly COPD); reassess frequently.', 'High-flow oxygen unless COPD is the immediate response to the distressed breathless patient (HCH9-0002).', TRUE),
   ('6c1bf955-13ed-54a4-a98e-c3feb41e1249', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-04', 'Obtain a 12-lead ECG', 'investigation', '40', 'Urgent 12-lead ECG: look for Q waves (previous MI), left ventricular hypertrophy, LBBB or dysrhythmia; in cardiogenic shock may show recent infarction or dysrhythmia.', 'ECG is urgent in the breathless patient and is usually abnormal in heart failure (HCH9-0002, HCH13-0002).', TRUE),
   ('e1c605e6-3b32-5fec-8e4e-4f961160fc32', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-05', 'Image the chest', 'investigation', '50', 'Chest X-ray: cardiac enlargement, congested lung fields, bilateral perihilar air-space consolidation; heart size should be <50% of thoracic width on PA film. Also excludes pneumothorax, pneumonia and large pleural effusions.', 'CXR is urgent and shows the congested cardiac pattern; cardiomegaly <50% thoracic width (HCH9-0002, HCH13-0002/0004, KCR-0019).', TRUE),
   ('c26fa153-2e9c-5b05-b07e-e4746d1b0eb9', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-06', 'Send BNP + renal function + blood count', 'investigation', '60', 'BNP (raised in diagnostic uncertainty), renal function as prelude to diuretic and ACE inhibitor therapy, and blood count to rule out anaemia.', 'BNP, renal function and FBC are the additional investigations in congestive heart failure (HCH13-0002).', TRUE),
   ('065559c1-3aa2-50c1-b6a7-eb401cc74242', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-07', 'Echocardiogram', 'investigation', '70', 'Echocardiogram - the single most important diagnostic test: LV dilatation with regional or global contractile impairment; exclude correctable valvular disease.', 'Echo confirms the diagnosis and guides therapy (HCH13-0002/0004).', TRUE),
   ('4736e9d9-35db-5efa-a1c4-38eac1d15a3e', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-08', 'Start diuretic + ACE inhibitor therapy (advice-level)', 'treatment', '80', 'Loop diuretic for congestion and an angiotensin converting enzyme (ACE) inhibitor once renal function is known; monitor weight, fluid balance, renal function and potassium. (Advice-level - verify doses against the local formulary.)', 'Renal function is the prelude to diuretic and ACE inhibitor therapy (HCH13-0002).', TRUE),
   ('3450e355-9cc7-5a39-a70b-50e87985bcdb', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-09', 'Monitor vital signs and daily weight', 'monitoring', '90', 'Monitor SpO2 (target according to comorbidity), heart rate, respiratory rate and daily body weight; track urine output and fluid balance.', 'Fluid retention tracking (daily weight) is central to decongestion in heart failure (HCH13-0005).', TRUE),
   ('78b2b3b2-3760-5e3a-846d-d59de76aec3a', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-10', 'Escalate if cardiogenic shock or deterioration', 'escalation', '100', 'If hypotension, oliguria, cool periphery, narrow pulse pressure or failure to improve: escalate urgently - inotropic support and invasive measures may be required; refer to critical care.', 'Cardiogenic shock requires inotropic support and invasive measures (HCH9-0003).', TRUE),
   ('53f9b70f-aa81-504b-9df5-f94796bc9f7e', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-11', 'Educate the patient and plan prevention', 'education', '110', 'Teach daily weight monitoring, salt/fluid restriction, medication adherence (diuretic + ACE inhibitor) and symptom recognition (orthopnoea, PND, leg swelling) with an action plan to seek care early.', 'Self-care reduces recurrent decompensation (HCH13-0005/0006).', TRUE),
   ('d7d447a9-18fa-5613-b207-80fb739c94c7', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), 'STEP-12', 'Close the care loop', 'follow_up', '120', 'Grade NYHA class (I-IV), document ECG/CXR/echo/BNP results, disposition, diuretic + ACE inhibitor plan and follow-up; reconsider the underlying cause (ischaemic, hypertensive, valvular, cardiomyopathy, alcohol).', 'Heart failure is chronic: the decompensation episode feeds ongoing maintenance and surveillance (HCH13-0002/0003).', TRUE)
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_action (id, protocol_id, step_id, action_type, action_code, action_name, detail, urgency, sort_order) VALUES
   ('8cb1f475-1589-5ac4-96d4-22ff23e9d2b5', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-01'), 'score', 'SCORE-NYHA', 'NYHA functional class', 'Grade NYHA I-IV from exertional symptom threshold (normal exertion / minimal exertion / at rest)', 'routine', '10'),
   ('1b6a90f6-bc8d-5028-87f4-d0c100077f34', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-SPO2', 'Oxygen saturation monitoring', 'Continuous in acute decompensation; target per comorbidity', 'immediate', '10'),
   ('ad426442-8524-5b07-9983-8d01822b69e1', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-HR', 'Heart rate monitoring', 'Tachycardia and dysrhythmia detection; cardiac apex rate in AF', 'immediate', '20'),
   ('b870f0d8-5b93-5bf8-bcbe-ff7183a97c76', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-02'), 'monitor', 'MON-RR', 'Respiratory rate monitoring', 'Tachypnoea and work of breathing', 'immediate', '30'),
   ('68eda89c-22a5-56b0-8ef5-e1e09d39665c', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-03'), 'advice', 'ADV-HF-POSITION', 'Sit the patient upright', 'Sitting upright reduces preload and work of breathing in pulmonary oedema', 'immediate', '10'),
   ('2a6e85fa-3a71-50d4-ae1c-f45e3698e001', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-03'), 'advice', 'ADV-HF-OXYGEN', 'High-flow oxygen unless COPD', 'High-flow O2 with reservoir unless known COPD / CO2 retention; reassess frequently', 'immediate', '20'),
   ('b67f2731-9a48-561e-937b-b445ce8ef3a5', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-04'), 'investigate', 'INV-ECG', '12-lead ECG', 'MI, LVH, LBBB, dysrhythmia; dynamic changes', 'urgent', '10'),
   ('6e3d87ac-e25f-504b-817a-7dee8af91386', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-05'), 'investigate', 'INV-CXR', 'Chest X-ray', 'Cardiac enlargement, congested lung fields, perihilar consolidation; exclude pneumothorax/effusion', 'urgent', '10'),
   ('eb35d4b6-b0e0-57c3-bee8-871b09ad64c9', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-06'), 'investigate', 'INV-BNP', 'B-type natriuretic peptide', 'Raised in heart failure; useful in diagnostic uncertainty', 'urgent', '10'),
   ('a9b7019c-3725-538e-b43d-fdb7fbaface4', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-06'), 'investigate', 'INV-UREA-CREAT', 'Renal function (urea/creatinine)', 'Prelude to diuretic + ACE inhibitor therapy', 'urgent', '20'),
   ('a7c9dffd-bb62-55a8-b599-ed25705066d6', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-06'), 'investigate', 'INV-FBC', 'Full blood count', 'Rule out anaemia as a driver of symptoms', 'routine', '30'),
   ('128075e9-438c-5151-a123-5d65f49d82dc', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-07'), 'investigate', 'INV-ECHO', 'Echocardiogram', 'Single most important test: LV dilatation + contractile impairment; exclude valvular disease', 'urgent', '10'),
   ('671cfbe0-f5fd-587a-bb1c-8847e702efb3', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-08'), 'advice', 'ADV-HF-DIURETIC', 'Loop diuretic (advice)', 'Loop diuretic for congestion once renal function known; monitor weight, fluid balance, electrolytes (advice-level - verify dose against local formulary)', 'urgent', '10'),
   ('d2bc03ee-aa1c-596e-b567-0fd65a6c34fa', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-08'), 'advice', 'ADV-HF-ACE', 'ACE inhibitor (advice)', 'ACE inhibitor once renal function known; monitor potassium and renal function (advice-level - verify dose against local formulary)', 'urgent', '20'),
   ('296bf767-34ac-5b41-9242-d1965c060a89', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-09'), 'monitor', 'MON-WEIGHT', 'Daily body weight', 'Daily weight tracks fluid retention/decongestion in heart failure', 'routine', '10'),
   ('96582061-8a76-55ad-b795-c37bf7221aac', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-09'), 'monitor', 'MON-SPO2', 'Oxygen saturation monitoring', 'Target per comorbidity; avoid excessive O2 in COPD', 'routine', '20'),
   ('b129b56b-5e44-5156-9f02-d522ba6b69de', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-10'), 'refer', 'REF-CRITICAL-CARE', 'Critical care referral', 'Cardiogenic shock: inotropic support + invasive measures', 'immediate', '10'),
   ('3bb22072-5e2d-5cc7-8e14-421733e9b28b', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-10'), 'refer', 'REF-CARDIOLOGY', 'Cardiology review', 'Specialist review for echo-guided management and underlying cause', 'urgent', '20'),
   ('ce51f9e7-b015-5cfa-ab01-cd7cdcdb584e', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-HF-SELF-CARE', 'Heart failure self-care', 'Daily weight, salt/fluid restriction, medication adherence, early symptom recognition', 'routine', '10'),
   ('c9420de4-0b2e-5b17-8759-f1709a6525dc', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-HF-DIET', 'Salt and fluid restriction', 'Reduce sodium intake; monitor fluid balance to prevent fluid retention', 'routine', '20'),
   ('f5e7b472-5b49-5f07-ac8a-92e8a6f69c3d', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-11'), 'educate', 'EDU-HF-SYMPTOM-RECOGNITION', 'Symptom recognition and action plan', 'Seek care early for increasing orthopnoea, PND, leg swelling or weight gain', 'routine', '30'),
   ('3796d1ce-c645-5d97-b3ca-aad98600918e', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT ps.id FROM knowledge.protocol_step ps JOIN knowledge.protocol p ON p.id = ps.protocol_id WHERE p.protocol_code = 'PROT-HF-DECOMP' AND ps.step_code = 'STEP-12'), 'educate', 'EDU-HF-CLINICIAN', 'Heart failure reasoning summary', 'Render NYHA class, ECG/CXR/echo/BNP evidence, diuretic + ACE plan, disposition and follow-up', 'routine', '10')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.protocol_monitoring (id, protocol_id, monitoring_id, frequency, deterioration_rule, escalation_instruction) VALUES
   ('9179464b-21f2-57a5-9ac9-5ca12e4ac6d1', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-SPO2'), 'Continuous during acute decompensation; target per comorbidity (avoid excessive O2 in COPD)', 'SpO2 <90% or falling despite oxygen, or rising work of breathing', 'Reassess severity; check ABG if available; escalate to critical care if cardiogenic shock'),
   ('3ac8e420-75c4-583d-8de0-f4038b0be53c', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-HR'), 'Continuous during acute decompensation', 'New dysrhythmia, uncontrolled tachycardia, or pulse deficit (AF)', 'Repeat ECG; senior/cardiology review'),
   ('76e28469-ffd0-540e-b1d1-c3c4b8c29b3f', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-RR'), 'Continuous during acute decompensation', 'Persistent tachypnoea or rising work of breathing', 'Reassess severity; consider CXR/ABG; escalate'),
   ('a5354e3f-afec-5a5c-8478-0d1fce4c048a', (SELECT id FROM knowledge.protocol WHERE protocol_code = 'PROT-HF-DECOMP'), (SELECT id FROM knowledge.monitoring WHERE monitoring_code = 'MON-WEIGHT'), 'Daily', 'Rapid weight gain (>2 kg over 1-2 days) reflecting fluid retention', 'Review diuretic dose, fluid balance and renal function')
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6. knowledge.education - heart failure education objects
-- ---------------------------------------------------------------------------
INSERT INTO knowledge.concept (id, concept_code, concept_type, canonical_name, display_name, status) VALUES
   ('89b21b74-875e-563c-ad0d-16cd042dcadf', 'CNS-EDU-HF-SELF-CARE', 'education', 'Heart failure self-care', 'Heart failure self-care', 'active'),
   ('c93a6c48-e9b5-50cd-ae00-13fd73b9fc55', 'CNS-EDU-HF-DIET', 'education', 'Salt and fluid restriction', 'Salt and fluid restriction', 'active'),
   ('1f65a5df-d0c3-544c-936f-e3227b10cc5c', 'CNS-EDU-HF-SYMPTOM-RECOGNITION', 'education', 'Symptom recognition and action plan', 'Symptom recognition and action plan', 'active'),
   ('5d345eae-0fed-58a5-9f30-43c3460a5df8', 'CNS-EDU-HF-CLINICIAN', 'education', 'Heart failure reasoning summary', 'Heart failure reasoning summary', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.education (id, concept_id, education_code, title, audience, content_type, language_code, literacy_level, body, status) VALUES
   ('81d00eb3-d5f0-5672-8d03-a44c59a75277', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-HF-SELF-CARE'), 'EDU-HF-SELF-CARE', 'Heart failure self-care', 'patient', 'instruction', 'en', 'plain', 'Weigh yourself daily, restrict salt and fluid, take diuretic and ACE inhibitor medicines as prescribed, and seek care early for increasing orthopnoea, paroxysmal nocturnal dyspnoea, leg swelling or rapid weight gain (HCH13-0002/0005).', 'active'),
   ('80d83d55-ca49-5456-9b42-48fede479931', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-HF-DIET'), 'EDU-HF-DIET', 'Salt and fluid restriction', 'patient', 'instruction', 'en', 'plain', 'Heart failure causes salt and water retention; reduce sodium intake and monitor fluid balance to prevent peripheral oedema and pulmonary congestion (HCH13-0005).', 'active'),
   ('57992246-3c25-5149-8ed2-9eafe984b6c8', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-HF-SYMPTOM-RECOGNITION'), 'EDU-HF-SYMPTOM-RECOGNITION', 'Symptom recognition and action plan', 'caregiver', 'discharge', 'en', 'plain', 'Rising JVP, basal crackles, pitting ankle/sacral oedema and orthopnoea signal congestion; rapid weight gain is an early warning. Seek care early rather than waiting for breathlessness at rest (HCH13-0001/0006).', 'active'),
   ('bc76acc3-12c0-5712-816e-3c80757f364a', (SELECT id FROM knowledge.concept WHERE concept_code = 'CNS-EDU-HF-CLINICIAN'), 'EDU-HF-CLINICIAN', 'Heart failure reasoning summary', 'clinician', 'explanation', 'en', 'plain', 'Render NYHA class, ECG/CXR/echo/BNP evidence, diuretic + ACE inhibitor plan, escalation threshold (cardiogenic shock), disposition and follow-up.', 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.education_condition (id, education_id, condition_id, weight) VALUES
   ('d807278f-6457-5ae9-910c-9ae8b59a6933', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-HF-SELF-CARE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), 1.0),
   ('46437826-375c-56bb-969f-b4683091ec2b', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-HF-SELF-CARE'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), 1.0),
   ('6206fa84-eb63-5861-aeed-07e8c6fb3637', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-HF-DIET'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), 1.0),
   ('25ebac62-0d41-57ac-824d-fb4eb668e724', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-HF-DIET'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), 1.0),
   ('de6a5351-8a86-59cf-ac61-f4216205798b', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-HF-SYMPTOM-RECOGNITION'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), 1.0),
   ('960b8917-d572-5965-a78c-f9b267627245', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-HF-SYMPTOM-RECOGNITION'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), 1.0),
   ('b1ce6b1d-ae85-59cc-a897-937b0fa31e5e', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-HF-CLINICIAN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'HEART_FAILURE'), 1.0),
   ('829bcf53-57cd-52a3-b178-969b5be21046', (SELECT id FROM knowledge.education WHERE education_code = 'EDU-HF-CLINICIAN'), (SELECT id FROM knowledge.condition WHERE condition_code = 'COND-HF-DECOMPENSATION'), 1.0)
  ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 7. governance.knowledge_object - heart failure pathway objects
-- ---------------------------------------------------------------------------
INSERT INTO governance.knowledge_object (id, object_code, knowledge_type, canonical_name, description, source_claim_code, jurisdiction_code, population_code, evidence_level_code, lifecycle_status, confidence, is_active, status) VALUES
   ('395584bb-f50b-54a1-9f9e-674fff1a7f55', 'PROT-HF-DECOMP', 'PROTOCOL', 'Acute heart failure decompensation pathway', 'Population-aware adult acute heart failure decompensation pathway: confirm decompensation, ABC + severity, upright positioning + high-flow oxygen unless COPD, ECG, CXR, BNP + renal + FBC, echo, advice-level diuretic + ACE inhibitor, monitoring (SpO2/HR/RR/daily weight), cardiogenic shock escalation, education and NYHA grading.', 'HCH13-0002', 'JUR-GLOBAL', 'POP-ADULT', 'EV-C', 'ACTIVE', 0.95, true, 'active'),
   ('967dd91b-0168-5350-97b3-7c752810c789', 'SCORE-NYHA', 'INTERPRETATION', 'NYHA functional classification', 'NYHA I-IV functional class from exertional dyspnoea threshold (normal exertion / minimal exertion / at rest), per Hutchison 24e Table 13.2 (HCH13-0003).', 'HCH13-0003', 'JUR-GLOBAL', 'POP-ADULT', 'EV-C', 'ACTIVE', 0.95, true, 'active'),
   ('b1d955cb-5e8c-59d2-a2e2-10a23ae0b40c', 'PHEN-CHF-CONGESTIVE', 'PHENOTYPE', 'Cardiopulmonary congestion phenotype', 'Dyspnoea + orthopnoea + PND + peripheral oedema + crackles pattern suggesting congestive heart failure decompensation (HCH13-0001/0004/0005).', 'HCH13-0001', 'JUR-GLOBAL', 'POP-ADULT', 'EV-C', 'ACTIVE', 0.95, true, 'active')
  ON CONFLICT DO NOTHING;

INSERT INTO governance.knowledge_object_version (object_id, version_no, version_code, change_note, lifecycle_status, source_claim_code, created_by)
SELECT ko.id, 1, 'GO-V-R7-' || ko.object_code, 'R7 heart failure decompensation pathway release (HCH13-0001..0006, HCH9-0001..0003, KCR-0019..0020).', 'ACTIVE', ko.source_claim_code, 'Dr A Otieno'
FROM governance.knowledge_object ko WHERE ko.object_code IN ('PROT-HF-DECOMP', 'SCORE-NYHA', 'PHEN-CHF-CONGESTIVE')
  ON CONFLICT DO NOTHING;

INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('efa90e54-fd49-54e1-884c-0c7d5966c688', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'HCH13-0002'), 'governance.knowledge_object', '395584bb-f50b-54a1-9f9e-674fff1a7f55', 'PROT-HF-DECOMP', 'derived_from')   ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('b81b60a4-e698-5e79-98d9-6a09dd9332bd', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'HCH13-0003'), 'governance.knowledge_object', '967dd91b-0168-5350-97b3-7c752810c789', 'SCORE-NYHA', 'derived_from')   ON CONFLICT DO NOTHING;
INSERT INTO knowledge.provenance (id, claim_id, object_type, object_id, object_code, relationship) VALUES ('6ed50743-fa91-51ec-8ead-bb7ce04beec4', (SELECT claim_id FROM knowledge.source_claim WHERE claim_code = 'HCH13-0001'), 'governance.knowledge_object', 'b1d955cb-5e8c-59d2-a2e2-10a23ae0b40c', 'PHEN-CHF-CONGESTIVE', 'derived_from')   ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 8. tracking.respiratory_master_matrix - heart failure status
-- ---------------------------------------------------------------------------
UPDATE tracking.respiratory_master_matrix SET status='VERIFIED', source_ground='Hutchison 24e p193-198 + Kumar & Clark 10e p929/937 (HCH13-0001..0006, KCR-0019/0020)',
       notes='Dyspnoea/orthopnoea/PND + heart failure differential: congestive heart failure, NYHA I-IV, acute LVF, oedema, JVP; ECG/CXR/echo/BNP investigations; adult decompensation pathway active.',
       updated_at=now() WHERE item_code='SYM-DYSPNOEA';
UPDATE tracking.respiratory_master_matrix SET status='GROUNDED', source_ground='Hutchison 24e p193 (Table 13.2, HCH13-0003)',
       notes='NYHA functional classification grades exercise limitation in heart failure (I asymptomatic - IV at rest).',
       updated_at=now() WHERE item_code='SYM-EXERCISE-INTOLERANCE';
INSERT INTO tracking.respiratory_master_matrix (id, family_code, family_name, item_code, item_name, population, status, source_ground, notes) VALUES
   ('ec1210d8-613d-5f1b-a38a-dffc46f09260', 'F', 'Pulmonary vascular disease', 'COND-HEART-FAILURE', 'Heart failure (congestive decompensation - cardiac cause of dyspnoea)', 'adult', 'VERIFIED', 'Hutchison 24e p193-198 + Kumar & Clark 10e p929/937 (HCH13-0001..0006, KCR-0019/0020)', 'Congestive heart failure + decompensation pathway with NYHA grading, ECG/CXR/echo/BNP, advice-level diuretic + ACE, cardiogenic shock escalation.'),
   ('9677a1be-5e99-510f-8f89-b7473ae44e15', 'F', 'Pulmonary vascular disease', 'COND-HF-DECOMPENSATION', 'Acute heart failure decompensation', 'adult', 'VERIFIED', 'Hutchison 24e p193/196/198 (HCH13-0001/0004/0005)', 'Acute congestion +/- low output; 12-step adult pathway PROT-HF-DECOMP active.')
  ON CONFLICT DO NOTHING;
